// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package circuitsdb

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"netbox_go/pkg/types"
)

type CircuitsCircuitPriority string

const (
	CircuitsCircuitPriorityPrimary   CircuitsCircuitPriority = "primary"
	CircuitsCircuitPrioritySecondary CircuitsCircuitPriority = "secondary"
	CircuitsCircuitPriorityTertiary  CircuitsCircuitPriority = "tertiary"
	CircuitsCircuitPriorityInactive  CircuitsCircuitPriority = "inactive"
)

func (e *CircuitsCircuitPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CircuitsCircuitPriority(s)
	case string:
		*e = CircuitsCircuitPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for CircuitsCircuitPriority: %T", src)
	}
	return nil
}

type NullCircuitsCircuitPriority struct {
	CircuitsCircuitPriority CircuitsCircuitPriority `json:"circuits_circuit_priority"`
	Valid                   bool                    `json:"valid"` // Valid is true if CircuitsCircuitPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCircuitsCircuitPriority) Scan(value interface{}) error {
	if value == nil {
		ns.CircuitsCircuitPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CircuitsCircuitPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCircuitsCircuitPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CircuitsCircuitPriority), nil
}

type CircuitsCircuitStatus string

const (
	CircuitsCircuitStatusPlanned        CircuitsCircuitStatus = "planned"
	CircuitsCircuitStatusProvisioning   CircuitsCircuitStatus = "provisioning"
	CircuitsCircuitStatusActive         CircuitsCircuitStatus = "active"
	CircuitsCircuitStatusOffline        CircuitsCircuitStatus = "offline"
	CircuitsCircuitStatusDeprovisioning CircuitsCircuitStatus = "deprovisioning"
	CircuitsCircuitStatusDecommissioned CircuitsCircuitStatus = "decommissioned"
)

func (e *CircuitsCircuitStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CircuitsCircuitStatus(s)
	case string:
		*e = CircuitsCircuitStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CircuitsCircuitStatus: %T", src)
	}
	return nil
}

type NullCircuitsCircuitStatus struct {
	CircuitsCircuitStatus CircuitsCircuitStatus `json:"circuits_circuit_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if CircuitsCircuitStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCircuitsCircuitStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CircuitsCircuitStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CircuitsCircuitStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCircuitsCircuitStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CircuitsCircuitStatus), nil
}

type CircuitsTerminationSide string

const (
	CircuitsTerminationSideA CircuitsTerminationSide = "A"
	CircuitsTerminationSideZ CircuitsTerminationSide = "Z"
)

func (e *CircuitsTerminationSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CircuitsTerminationSide(s)
	case string:
		*e = CircuitsTerminationSide(s)
	default:
		return fmt.Errorf("unsupported scan type for CircuitsTerminationSide: %T", src)
	}
	return nil
}

type NullCircuitsTerminationSide struct {
	CircuitsTerminationSide CircuitsTerminationSide `json:"circuits_termination_side"`
	Valid                   bool                    `json:"valid"` // Valid is true if CircuitsTerminationSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCircuitsTerminationSide) Scan(value interface{}) error {
	if value == nil {
		ns.CircuitsTerminationSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CircuitsTerminationSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCircuitsTerminationSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CircuitsTerminationSide), nil
}

type CircuitsVirtualCircuitTerminationRole string

const (
	CircuitsVirtualCircuitTerminationRolePeer  CircuitsVirtualCircuitTerminationRole = "peer"
	CircuitsVirtualCircuitTerminationRoleHub   CircuitsVirtualCircuitTerminationRole = "hub"
	CircuitsVirtualCircuitTerminationRoleSpoke CircuitsVirtualCircuitTerminationRole = "spoke"
)

func (e *CircuitsVirtualCircuitTerminationRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CircuitsVirtualCircuitTerminationRole(s)
	case string:
		*e = CircuitsVirtualCircuitTerminationRole(s)
	default:
		return fmt.Errorf("unsupported scan type for CircuitsVirtualCircuitTerminationRole: %T", src)
	}
	return nil
}

type NullCircuitsVirtualCircuitTerminationRole struct {
	CircuitsVirtualCircuitTerminationRole CircuitsVirtualCircuitTerminationRole `json:"circuits_virtual_circuit_termination_role"`
	Valid                                 bool                                  `json:"valid"` // Valid is true if CircuitsVirtualCircuitTerminationRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCircuitsVirtualCircuitTerminationRole) Scan(value interface{}) error {
	if value == nil {
		ns.CircuitsVirtualCircuitTerminationRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CircuitsVirtualCircuitTerminationRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCircuitsVirtualCircuitTerminationRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CircuitsVirtualCircuitTerminationRole), nil
}

// Физические телекоммуникационные цепи
type CircuitsCircuit struct {
	ID                types.ID                  `json:"id"`
	Cid               string                    `json:"cid"`
	ProviderID        types.ID                  `json:"provider_id"`
	ProviderAccountID uuid.NullUUID             `json:"provider_account_id"`
	TypeID            types.ID                  `json:"type_id"`
	Status            NullCircuitsCircuitStatus `json:"status"`
	TenantID          uuid.NullUUID             `json:"tenant_id"`
	InstallDate       sql.NullTime              `json:"install_date"`
	TerminationDate   sql.NullTime              `json:"termination_date"`
	// Committed rate в Kbps
	CommitRate sql.NullInt32 `json:"commit_rate"`
	// Длина цепи
	Distance sql.NullString `json:"distance"`
	// Единица измерения длины (km, m, mi, ft)
	DistanceUnit   sql.NullString `json:"distance_unit"`
	Description    sql.NullString `json:"description"`
	Comments       sql.NullString `json:"comments"`
	Created        sql.NullTime   `json:"created"`
	Updated        sql.NullTime   `json:"updated"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	TerminationAID uuid.NullUUID  `json:"termination_a_id"`
	TerminationZID uuid.NullUUID  `json:"termination_z_id"`
}

// Административные группы цепей
type CircuitsCircuitGroup struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	TenantID    uuid.NullUUID  `json:"tenant_id"`
	Description sql.NullString `json:"description"`
	Comments    sql.NullString `json:"comments"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

// Привязки цепей к группам
type CircuitsCircuitGroupAssignment struct {
	ID         types.ID                    `json:"id"`
	MemberType string                      `json:"member_type"`
	MemberID   types.ID                    `json:"member_id"`
	GroupID    types.ID                    `json:"group_id"`
	Priority   NullCircuitsCircuitPriority `json:"priority"`
	Created    sql.NullTime                `json:"created"`
	Updated    sql.NullTime                `json:"updated"`
}

// Точки завершения физических цепей
type CircuitsCircuitTermination struct {
	ID              types.ID                `json:"id"`
	CircuitID       types.ID                `json:"circuit_id"`
	TermSide        CircuitsTerminationSide `json:"term_side"`
	TerminationType sql.NullString          `json:"termination_type"`
	TerminationID   uuid.NullUUID           `json:"termination_id"`
	// Физическая скорость порта в Kbps
	PortSpeed sql.NullInt32 `json:"port_speed"`
	// Upstream скорость для асимметричных цепей в Kbps
	UpstreamSpeed sql.NullInt32 `json:"upstream_speed"`
	// ID локального кросс-коннекта
	XconnectID sql.NullString `json:"xconnect_id"`
	// ID патч-панели и номера портов
	PpInfo            sql.NullString `json:"pp_info"`
	Description       sql.NullString `json:"description"`
	Created           sql.NullTime   `json:"created"`
	Updated           sql.NullTime   `json:"updated"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	ProviderNetworkID uuid.NullUUID  `json:"_provider_network_id"`
	RegionID          uuid.NullUUID  `json:"_region_id"`
	SiteGroupID       uuid.NullUUID  `json:"_site_group_id"`
	SiteID            uuid.NullUUID  `json:"_site_id"`
	LocationID        uuid.NullUUID  `json:"_location_id"`
}

// Типы физических цепей
type CircuitsCircuitType struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Color       sql.NullString `json:"color"`
	Description sql.NullString `json:"description"`
	Comments    sql.NullString `json:"comments"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

// Провайдеры телекоммуникационных услуг
type CircuitsProvider struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	AsnIds      []types.ID     `json:"asn_ids"`
	Description sql.NullString `json:"description"`
	Comments    sql.NullString `json:"comments"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

// Аккаунты внутри провайдеров
type CircuitsProviderAccount struct {
	ID          types.ID       `json:"id"`
	ProviderID  types.ID       `json:"provider_id"`
	Account     string         `json:"account"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Comments    sql.NullString `json:"comments"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

// Сети провайдеров вне NetBox
type CircuitsProviderNetwork struct {
	ID          types.ID       `json:"id"`
	ProviderID  types.ID       `json:"provider_id"`
	Name        string         `json:"name"`
	ServiceID   sql.NullString `json:"service_id"`
	Description sql.NullString `json:"description"`
	Comments    sql.NullString `json:"comments"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

// Виртуальные соединения между эндпоинтами
type CircuitsVirtualCircuit struct {
	ID                types.ID                  `json:"id"`
	Cid               string                    `json:"cid"`
	ProviderNetworkID types.ID                  `json:"provider_network_id"`
	ProviderAccountID uuid.NullUUID             `json:"provider_account_id"`
	TypeID            types.ID                  `json:"type_id"`
	Status            NullCircuitsCircuitStatus `json:"status"`
	TenantID          uuid.NullUUID             `json:"tenant_id"`
	Description       sql.NullString            `json:"description"`
	Comments          sql.NullString            `json:"comments"`
	Created           sql.NullTime              `json:"created"`
	Updated           sql.NullTime              `json:"updated"`
	DeletedAt         sql.NullTime              `json:"deleted_at"`
}

// Точки завершения виртуальных цепей
type CircuitsVirtualCircuitTermination struct {
	ID               types.ID                                  `json:"id"`
	VirtualCircuitID types.ID                                  `json:"virtual_circuit_id"`
	Role             NullCircuitsVirtualCircuitTerminationRole `json:"role"`
	InterfaceID      types.ID                                  `json:"interface_id"`
	Description      sql.NullString                            `json:"description"`
	Created          sql.NullTime                              `json:"created"`
	Updated          sql.NullTime                              `json:"updated"`
	DeletedAt        sql.NullTime                              `json:"deleted_at"`
}

// Типы виртуальных цепей
type CircuitsVirtualCircuitType struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Color       sql.NullString `json:"color"`
	Description sql.NullString `json:"description"`
	Comments    sql.NullString `json:"comments"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}
