// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package circuitsdb

import (
	"context"

	"github.com/lib/pq"
)

const listProviders = `-- name: ListProviders :many
SELECT id, name, slug, asn_ids, description, comments, created, updated, deleted_at FROM circuits_providers ORDER BY name LIMIT $1 OFFSET $2
`

type ListProvidersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Circuits queries stub
func (q *Queries) ListProviders(ctx context.Context, arg ListProvidersParams) ([]CircuitsProvider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CircuitsProvider{}
	for rows.Next() {
		var i CircuitsProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			pq.Array(&i.AsnIds),
			&i.Description,
			&i.Comments,
			&i.Created,
			&i.Updated,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
