// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: queries.sql

package coredb

import (
"context"
"database/sql"
"encoding/json"
"time"

"netbox_go/pkg/types"
)

type DBTX interface {
ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
PrepareContext(context.Context, string) (*sql.Stmt, error)
QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

type Queries struct {
db DBTX
}

func New(db DBTX) *Queries {
return &Queries{db: db}
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
return &Queries{db: tx}
}

type GetConfigRevisionByIDRow struct {
ID      types.ID        `json:"id"`
Created time.Time       `json:"created"`
Active  bool            `json:"active"`
Comment sql.NullString  `json:"comment"`
Data    json.RawMessage `json:"data"`
}

const getConfigRevisionByID = `-- name: GetConfigRevisionByID :one
SELECT id, created, active, comment, data
FROM core_configrevision
WHERE id = $1
`

func (q *Queries) GetConfigRevisionByID(ctx context.Context, id types.ID) (GetConfigRevisionByIDRow, error) {
row := q.db.QueryRowContext(ctx, getConfigRevisionByID, id)
var i GetConfigRevisionByIDRow
err := row.Scan(&i.ID, &i.Created, &i.Active, &i.Comment, &i.Data)
return i, err
}

const getActiveConfigRevision = `-- name: GetActiveConfigRevision :one
SELECT id, created, active, comment, data
FROM core_configrevision
WHERE active = TRUE
ORDER BY created DESC
LIMIT 1
`

func (q *Queries) GetActiveConfigRevision(ctx context.Context) (GetConfigRevisionByIDRow, error) {
row := q.db.QueryRowContext(ctx, getActiveConfigRevision)
var i GetConfigRevisionByIDRow
err := row.Scan(&i.ID, &i.Created, &i.Active, &i.Comment, &i.Data)
return i, err
}

const listConfigRevisions = `-- name: ListConfigRevisions :many
SELECT id, created, active, comment, data
FROM core_configrevision
ORDER BY created DESC
LIMIT $1 OFFSET $2
`

func (q *Queries) ListConfigRevisions(ctx context.Context, limit, offset int32) ([]GetConfigRevisionByIDRow, error) {
rows, err := q.db.QueryContext(ctx, listConfigRevisions, limit, offset)
if err != nil {
return nil, err
}
defer rows.Close()
var items []GetConfigRevisionByIDRow
for rows.Next() {
var i GetConfigRevisionByIDRow
if err := rows.Scan(&i.ID, &i.Created, &i.Active, &i.Comment, &i.Data); err != nil {
return nil, err
}
items = append(items, i)
}
if err := rows.Close(); err != nil {
return nil, err
}
if err := rows.Err(); err != nil {
return nil, err
}
return items, nil
}

type CountConfigRevisionsRow struct {
Count int32 `json:"count"`
}

const countConfigRevisions = `-- name: CountConfigRevisions :one
SELECT COUNT(*)::int as count
FROM core_configrevision
`

func (q *Queries) CountConfigRevisions(ctx context.Context) (CountConfigRevisionsRow, error) {
row := q.db.QueryRowContext(ctx, countConfigRevisions)
var i CountConfigRevisionsRow
err := row.Scan(&i.Count)
return i, err
}

type CreateConfigRevisionParams struct {
Created time.Time
Active  bool
Comment sql.NullString
Data    json.RawMessage
}

const createConfigRevision = `-- name: CreateConfigRevision :one
INSERT INTO core_configrevision (created, active, comment, data)
VALUES ($1, $2, $3, $4)
RETURNING id, created, active, comment, data
`

func (q *Queries) CreateConfigRevision(ctx context.Context, arg CreateConfigRevisionParams) (GetConfigRevisionByIDRow, error) {
row := q.db.QueryRowContext(ctx, createConfigRevision,
arg.Created,
arg.Active,
arg.Comment,
arg.Data,
)
var i GetConfigRevisionByIDRow
err := row.Scan(&i.ID, &i.Created, &i.Active, &i.Comment, &i.Data)
return i, err
}

type UpdateConfigRevisionParams struct {
ID      types.ID
Active  bool
Comment sql.NullString
Data    json.RawMessage
}

const updateConfigRevision = `-- name: UpdateConfigRevision :execrows
UPDATE core_configrevision
SET active = $2, comment = $3, data = $4
WHERE id = $1
`

func (q *Queries) UpdateConfigRevision(ctx context.Context, arg UpdateConfigRevisionParams) (int64, error) {
result, err := q.db.ExecContext(ctx, updateConfigRevision,
arg.ID,
arg.Active,
arg.Comment,
arg.Data,
)
if err != nil {
return 0, err
}
return result.RowsAffected()
}

const deleteConfigRevision = `-- name: DeleteConfigRevision :execrows
DELETE FROM core_configrevision
WHERE id = $1
`

func (q *Queries) DeleteConfigRevision(ctx context.Context, id types.ID) (int64, error) {
result, err := q.db.ExecContext(ctx, deleteConfigRevision, id)
if err != nil {
return 0, err
}
return result.RowsAffected()
}

const setActiveConfigRevision = `-- name: SetActiveConfigRevision :execrows
UPDATE core_configrevision
SET active = FALSE
WHERE active = TRUE;

UPDATE core_configrevision
SET active = TRUE
WHERE id = $1
`

func (q *Queries) SetActiveConfigRevision(ctx context.Context, id types.ID) error {
	_, err := q.db.ExecContext(ctx, setActiveConfigRevision, id)
	return err
}

// ============================================================================
// JSON Helper Functions
// ============================================================================

const getJSONField = `-- name: GetJSONField :one
SELECT data->>$2 as value
FROM core_configrevision
WHERE id = $1
`

func (q *Queries) GetJSONField(ctx context.Context, id types.ID, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getJSONField, id, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const mergeJSONData = `-- name: MergeJSONData :execrows
UPDATE core_configrevision
SET data = COALESCE(data, '{}'::jsonb)::jsonb || $2::jsonb
WHERE id = $1
`

func (q *Queries) MergeJSONData(ctx context.Context, id types.ID, jsonData json.RawMessage) (int64, error) {
	result, err := q.db.ExecContext(ctx, mergeJSONData, id, jsonData)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// ============================================================================
// Additional ObjectChange Queries  
// ============================================================================

type GetObjectChangesByObjectTypeRow struct {
	ID                 types.ID        `json:"id"`
	Time               time.Time       `json:"time"`
	UserID             sql.NullString  `json:"user_id"`
	RequestID          sql.NullString  `json:"request_id"`
	Action             string          `json:"action"`
	ChangedObjectType  string          `json:"changed_object_type"`
	ChangedObjectID    string          `json:"changed_object_id"`
	ObjectRepr         string          `json:"object_repr"`
	ObjectData         json.RawMessage `json:"object_data"`
	RelatedObjectType  sql.NullString  `json:"related_object_type"`
	RelatedObjectID    sql.NullString  `json:"related_object_id"`
	RelatedObjectRepr  sql.NullString  `json:"related_object_repr"`
}

const getObjectChangesByObjectType = `-- name: GetObjectChangesByObjectType :many
SELECT 
    id, time, user_id, request_id, action, changed_object_type, 
    changed_object_id, object_repr, object_data, related_object_type,
    related_object_id, related_object_repr
FROM core_objectchange
WHERE changed_object_type = $1
ORDER BY time DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) GetObjectChangesByObjectType(ctx context.Context, objectType string, limit, offset int32) ([]GetObjectChangesByObjectTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getObjectChangesByObjectType, objectType, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetObjectChangesByObjectTypeRow
	for rows.Next() {
		var i GetObjectChangesByObjectTypeRow
		if err := rows.Scan(&i.ID, &i.Time, &i.UserID, &i.RequestID, &i.Action, 
			&i.ChangedObjectType, &i.ChangedObjectID, &i.ObjectRepr, &i.ObjectData,
			&i.RelatedObjectType, &i.RelatedObjectID, &i.RelatedObjectRepr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ============================================================================
// Additional DataSource Queries
// ============================================================================

type GetEnabledDataSourcesRow struct {
	ID            types.ID        `json:"id"`
	Name          string          `json:"name"`
	Type          string          `json:"type"`
	SourceURL     string          `json:"source_url"`
	Status        string          `json:"status"`
	Enabled       bool            `json:"enabled"`
	SyncInterval  sql.NullInt32   `json:"sync_interval"`
	IgnoreRules   json.RawMessage `json:"ignore_rules"`
	Parameters    json.RawMessage `json:"parameters"`
	LastSynced    sql.NullTime    `json:"last_synced"`
	Created       time.Time       `json:"created"`
	Updated       time.Time       `json:"updated"`
}

const getEnabledDataSources = `-- name: GetEnabledDataSources :many
SELECT 
    id, name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
FROM core_datasource
WHERE enabled = TRUE
ORDER BY name
`

func (q *Queries) GetEnabledDataSources(ctx context.Context) ([]GetEnabledDataSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledDataSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnabledDataSourcesRow
	for rows.Next() {
		var i GetEnabledDataSourcesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Type, &i.SourceURL, &i.Status, &i.Enabled,
			&i.SyncInterval, &i.IgnoreRules, &i.Parameters, &i.LastSynced, &i.Created, &i.Updated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataSourceLastSynced = `-- name: UpdateDataSourceLastSynced :execrows
UPDATE core_datasource
SET last_synced = $2, updated = NOW()
WHERE id = $1
`

func (q *Queries) UpdateDataSourceLastSynced(ctx context.Context, id types.ID, lastSynced time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDataSourceLastSynced, id, lastSynced)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// ============================================================================
// Additional Job Queries
// ============================================================================

type GetJobStatisticsRow struct {
	PendingCount   int32 `json:"pending_count"`
	RunningCount   int32 `json:"running_count"`
	CompletedCount int32 `json:"completed_count"`
	FailedCount    int32 `json:"failed_count"`
	ScheduledCount int32 `json:"scheduled_count"`
}

const getJobStatistics = `-- name: GetJobStatistics :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'pending')::int as pending_count,
    COUNT(*) FILTER (WHERE status = 'running')::int as running_count,
    COUNT(*) FILTER (WHERE status = 'completed')::int as completed_count,
    COUNT(*) FILTER (WHERE status = 'failed')::int as failed_count,
    COUNT(*) FILTER (WHERE status = 'scheduled')::int as scheduled_count
FROM core_job
`

func (q *Queries) GetJobStatistics(ctx context.Context) (GetJobStatisticsRow, error) {
	row := q.db.QueryRowContext(ctx, getJobStatistics)
	var i GetJobStatisticsRow
	err := row.Scan(&i.PendingCount, &i.RunningCount, &i.CompletedCount, &i.FailedCount, &i.ScheduledCount)
	return i, err
}

const cancelScheduledJob = `-- name: CancelScheduledJob :execrows
UPDATE core_job
SET status = 'cancelled', completed_at = NOW(), updated = NOW()
WHERE id = $1 AND status = 'scheduled'
`

func (q *Queries) CancelScheduledJob(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelScheduledJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryFailedJob = `-- name: RetryFailedJob :execrows
UPDATE core_job
SET status = 'pending', error = NULL, completed_at = NULL, updated = NOW()
WHERE id = $1 AND status IN ('failed', 'errored')
`

func (q *Queries) RetryFailedJob(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryFailedJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
