// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coredb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
	"netbox_go/pkg/types"
)

// Ревизии конфигурации NetBox
type CoreConfigrevision struct {
	// Первичный ключ
	ID types.ID `json:"id"`
	// Дата создания ревизии
	Created time.Time `json:"created"`
	// Флаг активной ревизии
	Active bool `json:"active"`
	// Комментарий к ревизии
	Comment sql.NullString `json:"comment"`
	// Данные конфигурации в формате JSON
	Data json.RawMessage `json:"data"`
}

// Файлы данных из источников
type CoreDatafile struct {
	ID types.ID `json:"id"`
	// Ссылка на источник данных
	SourceID types.ID `json:"source_id"`
	// Путь к файлу относительно источника
	Path string `json:"path"`
	// Размер файла в байтах
	Size int64 `json:"size"`
	// Хэш содержимого файла (SHA256)
	Hash string `json:"hash"`
	// Парсенные данные файла (если применимо)
	Data    pqtype.NullRawMessage `json:"data"`
	Created time.Time             `json:"created"`
	Updated time.Time             `json:"updated"`
}

// Источники внешних данных
type CoreDatasource struct {
	ID types.ID `json:"id"`
	// Уникальное имя источника
	Name string `json:"name"`
	// Тип источника (git, http, local, etc.)
	Type string `json:"type"`
	// URL или путь к источнику
	SourceUrl string `json:"source_url"`
	// Статус источника
	Status string `json:"status"`
	// Флаг включения
	Enabled bool `json:"enabled"`
	// Интервал синхронизации в минутах
	SyncInterval int32 `json:"sync_interval"`
	// Правила игнорирования файлов
	IgnoreRules pqtype.NullRawMessage `json:"ignore_rules"`
	// Параметры подключения
	Parameters pqtype.NullRawMessage `json:"parameters"`
	// Время последней синхронизации
	LastSynced sql.NullTime `json:"last_synced"`
	Created    time.Time    `json:"created"`
	Updated    time.Time    `json:"updated"`
}

// Фоновые задачи
type CoreJob struct {
	ID types.ID `json:"id"`
	// Тип связанного объекта
	ObjectType sql.NullString `json:"object_type"`
	// ID связанного объекта
	ObjectID uuid.NullUUID `json:"object_id"`
	// Имя задачи
	Name string `json:"name"`
	// Статус выполнения
	Status string `json:"status"`
	// Интервал повторения в минутах
	Interval sql.NullInt32 `json:"interval"`
	// Время запланированного запуска
	ScheduledAt sql.NullTime `json:"scheduled_at"`
	// Время начала выполнения
	StartedAt sql.NullTime `json:"started_at"`
	// Время завершения
	CompletedAt sql.NullTime `json:"completed_at"`
	// Имя очереди etcd
	QueueName sql.NullString `json:"queue_name"`
	// Внешний ID задачи в системе очередей
	JobID sql.NullString `json:"job_id"`
	// Параметры задачи
	Data pqtype.NullRawMessage `json:"data"`
	// Сообщение об ошибке
	Error   sql.NullString `json:"error"`
	Created time.Time      `json:"created"`
	Updated time.Time      `json:"updated"`
}

// Журнал изменений объектов
type CoreObjectchange struct {
	ID types.ID `json:"id"`
	// Время изменения
	Time time.Time `json:"time"`
	// ID пользователя, внёсшего изменение
	UserID uuid.NullUUID `json:"user_id"`
	// ID HTTP запроса
	RequestID sql.NullString `json:"request_id"`
	// Тип действия (create/update/delete)
	Action string `json:"action"`
	// Тип изменённого объекта
	ChangedObjectType string `json:"changed_object_type"`
	// ID изменённого объекта
	ChangedObjectID string `json:"changed_object_id"`
	// Строковое представление объекта
	ObjectRepr string `json:"object_repr"`
	// Данные объекта до/после изменения
	ObjectData pqtype.NullRawMessage `json:"object_data"`
	// Тип связанного объекта
	RelatedObjectType sql.NullString `json:"related_object_type"`
	// ID связанного объекта
	RelatedObjectID sql.NullString `json:"related_object_id"`
	// Представление связанного объекта
	RelatedObjectRepr sql.NullString `json:"related_object_repr"`
}

// Типы объектов (аналог Django ContentType)
type DjangoContentType struct {
	ID types.ID `json:"id"`
	// Метка приложения
	AppLabel string `json:"app_label"`
	// Имя модели
	Model string `json:"model"`
	// Публичный тип объекта
	Public bool `json:"public"`
	// Список поддерживаемых функций
	Features pqtype.NullRawMessage `json:"features"`
	Created  time.Time             `json:"created"`
	Updated  time.Time             `json:"updated"`
}
