// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package coredb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"netbox_go/pkg/types"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const archiveCompletedJobs = `-- name: ArchiveCompletedJobs :execrows
UPDATE core_job
SET data = NULL
WHERE status IN ('completed', 'cancelled')
  AND completed_at < $1
  AND data IS NOT NULL
`

func (q *Queries) ArchiveCompletedJobs(ctx context.Context, completedAt sql.NullTime) (int64, error) {
	result, err := q.DB.ExecContext(ctx, archiveCompletedJobs, completedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bulkCreateObjectChanges = `-- name: BulkCreateObjectChanges :exec
INSERT INTO core_objectchange (
    time, user_id, request_id, action, changed_object_type,
    changed_object_id, object_repr, object_data, related_object_type,
    related_object_id, related_object_repr
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type BulkCreateObjectChangesParams struct {
	Time              time.Time             `json:"time"`
	UserID            uuid.NullUUID         `json:"user_id"`
	RequestID         sql.NullString        `json:"request_id"`
	Action            string                `json:"action"`
	ChangedObjectType string                `json:"changed_object_type"`
	ChangedObjectID   string                `json:"changed_object_id"`
	ObjectRepr        string                `json:"object_repr"`
	ObjectData        pqtype.NullRawMessage `json:"object_data"`
	RelatedObjectType sql.NullString        `json:"related_object_type"`
	RelatedObjectID   sql.NullString        `json:"related_object_id"`
	RelatedObjectRepr sql.NullString        `json:"related_object_repr"`
}

func (q *Queries) BulkCreateObjectChanges(ctx context.Context, arg BulkCreateObjectChangesParams) error {
	_, err := q.DB.ExecContext(ctx, bulkCreateObjectChanges,
		arg.Time,
		arg.UserID,
		arg.RequestID,
		arg.Action,
		arg.ChangedObjectType,
		arg.ChangedObjectID,
		arg.ObjectRepr,
		arg.ObjectData,
		arg.RelatedObjectType,
		arg.RelatedObjectID,
		arg.RelatedObjectRepr,
	)
	return err
}

const bulkDeleteDataFilesBySource = `-- name: BulkDeleteDataFilesBySource :execrows
DELETE FROM core_datafile
WHERE source_id = $1
`

func (q *Queries) BulkDeleteDataFilesBySource(ctx context.Context, sourceID types.ID) (int64, error) {
	result, err := q.DB.ExecContext(ctx, bulkDeleteDataFilesBySource, sourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bulkDeleteOldObjectChanges = `-- name: BulkDeleteOldObjectChanges :execrows
DELETE FROM core_objectchange
WHERE id IN (
    SELECT id FROM core_objectchange
    WHERE ($1::timestamp WITH TIME ZONE IS NULL OR time < $1)
    ORDER BY time DESC
    OFFSET $2
)
`

type BulkDeleteOldObjectChangesParams struct {
	Column1 time.Time `json:"column_1"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) BulkDeleteOldObjectChanges(ctx context.Context, arg BulkDeleteOldObjectChangesParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, bulkDeleteOldObjectChanges, arg.Column1, arg.Offset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bulkUpdateObjectTypes = `-- name: BulkUpdateObjectTypes :exec

INSERT INTO django_content_type (app_label, model, public, features, created, updated)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (app_label, model) DO UPDATE SET
    public = EXCLUDED.public,
    features = EXCLUDED.features,
    updated = EXCLUDED.updated
`

type BulkUpdateObjectTypesParams struct {
	AppLabel string                `json:"app_label"`
	Model    string                `json:"model"`
	Public   bool                  `json:"public"`
	Features pqtype.NullRawMessage `json:"features"`
	Created  time.Time             `json:"created"`
	Updated  time.Time             `json:"updated"`
}

// ============================================================================
// Bulk Operations
// ============================================================================
func (q *Queries) BulkUpdateObjectTypes(ctx context.Context, arg BulkUpdateObjectTypesParams) error {
	_, err := q.DB.ExecContext(ctx, bulkUpdateObjectTypes,
		arg.AppLabel,
		arg.Model,
		arg.Public,
		arg.Features,
		arg.Created,
		arg.Updated,
	)
	return err
}

const cancelScheduledJob = `-- name: CancelScheduledJob :execrows
UPDATE core_job
SET status = 'cancelled', completed_at = NOW(), updated = NOW()
WHERE id = $1 AND status = 'scheduled'
`

func (q *Queries) CancelScheduledJob(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.DB.ExecContext(ctx, cancelScheduledJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cleanupOldJobs = `-- name: CleanupOldJobs :execrows
DELETE FROM core_job
WHERE status IN ('completed', 'failed', 'errored') 
  AND completed_at < $1
`

func (q *Queries) CleanupOldJobs(ctx context.Context, completedAt sql.NullTime) (int64, error) {
	result, err := q.DB.ExecContext(ctx, cleanupOldJobs, completedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countConfigRevisions = `-- name: CountConfigRevisions :one
SELECT COUNT(*)::int as count
FROM core_configrevision
`

func (q *Queries) CountConfigRevisions(ctx context.Context) (int32, error) {
	row := q.DB.QueryRowContext(ctx, countConfigRevisions)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countDataFilesBySource = `-- name: CountDataFilesBySource :one
SELECT COUNT(*)::int as count
FROM core_datafile
WHERE source_id = $1
`

func (q *Queries) CountDataFilesBySource(ctx context.Context, sourceID types.ID) (int32, error) {
	row := q.DB.QueryRowContext(ctx, countDataFilesBySource, sourceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countDataFilesTotal = `-- name: CountDataFilesTotal :one
SELECT COUNT(*)::int as count
FROM core_datafile
`

func (q *Queries) CountDataFilesTotal(ctx context.Context) (int32, error) {
	row := q.DB.QueryRowContext(ctx, countDataFilesTotal)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countDataSources = `-- name: CountDataSources :one
SELECT COUNT(*)::int as count
FROM core_datasource
WHERE ($1 = '' OR status = $1)
  AND ($2::boolean IS NULL OR enabled = $2)
  AND ($3 = '' OR type = $3)
`

type CountDataSourcesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 bool        `json:"column_2"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) CountDataSources(ctx context.Context, arg CountDataSourcesParams) (int32, error) {
	row := q.DB.QueryRowContext(ctx, countDataSources, arg.Column1, arg.Column2, arg.Column3)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*)::int as count
FROM core_job
WHERE ($1 = '' OR status = $1)
  AND ($2 = '' OR object_type = $2)
  AND ($3::uuid IS NULL OR object_id = $3)
  AND ($4 = '' OR queue_name = $4)
`

type CountJobsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 types.ID    `json:"column_3"`
	Column4 interface{} `json:"column_4"`
}

func (q *Queries) CountJobs(ctx context.Context, arg CountJobsParams) (int32, error) {
	row := q.DB.QueryRowContext(ctx, countJobs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countObjectChanges = `-- name: CountObjectChanges :one
SELECT COUNT(*)::int as count
FROM core_objectchange
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2 = '' OR action = $2)
  AND ($3 = '' OR changed_object_type = $3)
  AND ($4 = '' OR changed_object_id = $4)
  AND ($5::timestamp WITH TIME ZONE IS NULL OR time >= $5)
  AND ($6::timestamp WITH TIME ZONE IS NULL OR time <= $6)
`

type CountObjectChangesParams struct {
	Column1 types.ID    `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 time.Time   `json:"column_5"`
	Column6 time.Time   `json:"column_6"`
}

func (q *Queries) CountObjectChanges(ctx context.Context, arg CountObjectChangesParams) (int32, error) {
	row := q.DB.QueryRowContext(ctx, countObjectChanges,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countObjectTypes = `-- name: CountObjectTypes :one
SELECT COUNT(*)::int as count
FROM django_content_type
WHERE ($1 = '' OR app_label = $1)
  AND ($2 = '' OR model = $2)
  AND ($3::boolean IS NULL OR public = $3)
`

type CountObjectTypesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 bool        `json:"column_3"`
}

func (q *Queries) CountObjectTypes(ctx context.Context, arg CountObjectTypesParams) (int32, error) {
	row := q.DB.QueryRowContext(ctx, countObjectTypes, arg.Column1, arg.Column2, arg.Column3)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createConfigRevision = `-- name: CreateConfigRevision :one
INSERT INTO core_configrevision (created, active, comment, data)
VALUES ($1, $2, $3, $4)
RETURNING id, created, active, comment, data
`

type CreateConfigRevisionParams struct {
	Created time.Time       `json:"created"`
	Active  bool            `json:"active"`
	Comment sql.NullString  `json:"comment"`
	Data    json.RawMessage `json:"data"`
}

func (q *Queries) CreateConfigRevision(ctx context.Context, arg CreateConfigRevisionParams) (CoreConfigrevision, error) {
	row := q.DB.QueryRowContext(ctx, createConfigRevision,
		arg.Created,
		arg.Active,
		arg.Comment,
		arg.Data,
	)
	var i CoreConfigrevision
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Active,
		&i.Comment,
		&i.Data,
	)
	return i, err
}

const createDataFile = `-- name: CreateDataFile :one
INSERT INTO core_datafile (source_id, path, size, hash, data, created, updated)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, source_id, path, size, hash, data, created, updated
`

type CreateDataFileParams struct {
	SourceID types.ID              `json:"source_id"`
	Path     string                `json:"path"`
	Size     int64                 `json:"size"`
	Hash     string                `json:"hash"`
	Data     pqtype.NullRawMessage `json:"data"`
	Created  time.Time             `json:"created"`
	Updated  time.Time             `json:"updated"`
}

func (q *Queries) CreateDataFile(ctx context.Context, arg CreateDataFileParams) (CoreDatafile, error) {
	row := q.DB.QueryRowContext(ctx, createDataFile,
		arg.SourceID,
		arg.Path,
		arg.Size,
		arg.Hash,
		arg.Data,
		arg.Created,
		arg.Updated,
	)
	var i CoreDatafile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Path,
		&i.Size,
		&i.Hash,
		&i.Data,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createDataSource = `-- name: CreateDataSource :one
INSERT INTO core_datasource (
    name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING 
    id, name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
`

type CreateDataSourceParams struct {
	Name         string                `json:"name"`
	Type         string                `json:"type"`
	SourceUrl    string                `json:"source_url"`
	Status       string                `json:"status"`
	Enabled      bool                  `json:"enabled"`
	SyncInterval int32                 `json:"sync_interval"`
	IgnoreRules  pqtype.NullRawMessage `json:"ignore_rules"`
	Parameters   pqtype.NullRawMessage `json:"parameters"`
	LastSynced   sql.NullTime          `json:"last_synced"`
	Created      time.Time             `json:"created"`
	Updated      time.Time             `json:"updated"`
}

func (q *Queries) CreateDataSource(ctx context.Context, arg CreateDataSourceParams) (CoreDatasource, error) {
	row := q.DB.QueryRowContext(ctx, createDataSource,
		arg.Name,
		arg.Type,
		arg.SourceUrl,
		arg.Status,
		arg.Enabled,
		arg.SyncInterval,
		arg.IgnoreRules,
		arg.Parameters,
		arg.LastSynced,
		arg.Created,
		arg.Updated,
	)
	var i CoreDatasource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.SourceUrl,
		&i.Status,
		&i.Enabled,
		&i.SyncInterval,
		&i.IgnoreRules,
		&i.Parameters,
		&i.LastSynced,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO core_job (
    object_type, object_id, name, status, interval, scheduled_at,
    started_at, completed_at, queue_name, job_id, data, error, created, updated
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING 
    id, object_type, object_id, name, status, interval, scheduled_at,
    started_at, completed_at, queue_name, job_id, data, error, created, updated
`

type CreateJobParams struct {
	ObjectType  sql.NullString        `json:"object_type"`
	ObjectID    uuid.NullUUID         `json:"object_id"`
	Name        string                `json:"name"`
	Status      string                `json:"status"`
	Interval    sql.NullInt32         `json:"interval"`
	ScheduledAt sql.NullTime          `json:"scheduled_at"`
	StartedAt   sql.NullTime          `json:"started_at"`
	CompletedAt sql.NullTime          `json:"completed_at"`
	QueueName   sql.NullString        `json:"queue_name"`
	JobID       sql.NullString        `json:"job_id"`
	Data        pqtype.NullRawMessage `json:"data"`
	Error       sql.NullString        `json:"error"`
	Created     time.Time             `json:"created"`
	Updated     time.Time             `json:"updated"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (CoreJob, error) {
	row := q.DB.QueryRowContext(ctx, createJob,
		arg.ObjectType,
		arg.ObjectID,
		arg.Name,
		arg.Status,
		arg.Interval,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.QueueName,
		arg.JobID,
		arg.Data,
		arg.Error,
		arg.Created,
		arg.Updated,
	)
	var i CoreJob
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Name,
		&i.Status,
		&i.Interval,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.QueueName,
		&i.JobID,
		&i.Data,
		&i.Error,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createObjectChange = `-- name: CreateObjectChange :one
INSERT INTO core_objectchange (
    time, user_id, request_id, action, changed_object_type, 
    changed_object_id, object_repr, object_data, related_object_type,
    related_object_id, related_object_repr
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING 
    id, time, user_id, request_id, action, changed_object_type, 
    changed_object_id, object_repr, object_data, related_object_type,
    related_object_id, related_object_repr
`

type CreateObjectChangeParams struct {
	Time              time.Time             `json:"time"`
	UserID            uuid.NullUUID         `json:"user_id"`
	RequestID         sql.NullString        `json:"request_id"`
	Action            string                `json:"action"`
	ChangedObjectType string                `json:"changed_object_type"`
	ChangedObjectID   string                `json:"changed_object_id"`
	ObjectRepr        string                `json:"object_repr"`
	ObjectData        pqtype.NullRawMessage `json:"object_data"`
	RelatedObjectType sql.NullString        `json:"related_object_type"`
	RelatedObjectID   sql.NullString        `json:"related_object_id"`
	RelatedObjectRepr sql.NullString        `json:"related_object_repr"`
}

func (q *Queries) CreateObjectChange(ctx context.Context, arg CreateObjectChangeParams) (CoreObjectchange, error) {
	row := q.DB.QueryRowContext(ctx, createObjectChange,
		arg.Time,
		arg.UserID,
		arg.RequestID,
		arg.Action,
		arg.ChangedObjectType,
		arg.ChangedObjectID,
		arg.ObjectRepr,
		arg.ObjectData,
		arg.RelatedObjectType,
		arg.RelatedObjectID,
		arg.RelatedObjectRepr,
	)
	var i CoreObjectchange
	err := row.Scan(
		&i.ID,
		&i.Time,
		&i.UserID,
		&i.RequestID,
		&i.Action,
		&i.ChangedObjectType,
		&i.ChangedObjectID,
		&i.ObjectRepr,
		&i.ObjectData,
		&i.RelatedObjectType,
		&i.RelatedObjectID,
		&i.RelatedObjectRepr,
	)
	return i, err
}

const createObjectType = `-- name: CreateObjectType :one
INSERT INTO django_content_type (app_label, model, public, features, created, updated)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, app_label, model, public, features, created, updated
`

type CreateObjectTypeParams struct {
	AppLabel string                `json:"app_label"`
	Model    string                `json:"model"`
	Public   bool                  `json:"public"`
	Features pqtype.NullRawMessage `json:"features"`
	Created  time.Time             `json:"created"`
	Updated  time.Time             `json:"updated"`
}

func (q *Queries) CreateObjectType(ctx context.Context, arg CreateObjectTypeParams) (DjangoContentType, error) {
	row := q.DB.QueryRowContext(ctx, createObjectType,
		arg.AppLabel,
		arg.Model,
		arg.Public,
		arg.Features,
		arg.Created,
		arg.Updated,
	)
	var i DjangoContentType
	err := row.Scan(
		&i.ID,
		&i.AppLabel,
		&i.Model,
		&i.Public,
		&i.Features,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteConfigRevision = `-- name: DeleteConfigRevision :execrows
DELETE FROM core_configrevision
WHERE id = $1
`

func (q *Queries) DeleteConfigRevision(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.DB.ExecContext(ctx, deleteConfigRevision, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDataFile = `-- name: DeleteDataFile :execrows
DELETE FROM core_datafile
WHERE id = $1
`

func (q *Queries) DeleteDataFile(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.DB.ExecContext(ctx, deleteDataFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDataSource = `-- name: DeleteDataSource :execrows
DELETE FROM core_datasource
WHERE id = $1
`

func (q *Queries) DeleteDataSource(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.DB.ExecContext(ctx, deleteDataSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteJob = `-- name: DeleteJob :execrows
DELETE FROM core_job
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.DB.ExecContext(ctx, deleteJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteObjectType = `-- name: DeleteObjectType :execrows
DELETE FROM django_content_type
WHERE id = $1
`

func (q *Queries) DeleteObjectType(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.DB.ExecContext(ctx, deleteObjectType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOldObjectChanges = `-- name: DeleteOldObjectChanges :execrows
DELETE FROM core_objectchange
WHERE time < $1
`

func (q *Queries) DeleteOldObjectChanges(ctx context.Context, argTime time.Time) (int64, error) {
	result, err := q.DB.ExecContext(ctx, deleteOldObjectChanges, argTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveConfigRevision = `-- name: GetActiveConfigRevision :one
SELECT 
    id, created, active, comment, data
FROM core_configrevision
WHERE active = TRUE
ORDER BY created DESC
LIMIT 1
`

func (q *Queries) GetActiveConfigRevision(ctx context.Context) (CoreConfigrevision, error) {
	row := q.DB.QueryRowContext(ctx, getActiveConfigRevision)
	var i CoreConfigrevision
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Active,
		&i.Comment,
		&i.Data,
	)
	return i, err
}

const getConfigRevisionByID = `-- name: GetConfigRevisionByID :one

SELECT 
    id, created, active, comment, data
FROM core_configrevision
WHERE id = $1
`

// Название: core
// Описание: SQL запросы для работы с таблицами модуля Core NetBox
// Версия: 1.0.0
func (q *Queries) GetConfigRevisionByID(ctx context.Context, id types.ID) (CoreConfigrevision, error) {
	row := q.DB.QueryRowContext(ctx, getConfigRevisionByID, id)
	var i CoreConfigrevision
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Active,
		&i.Comment,
		&i.Data,
	)
	return i, err
}

const getDataFileByID = `-- name: GetDataFileByID :one
SELECT 
    id, source_id, path, size, hash, data, created, updated
FROM core_datafile
WHERE id = $1
`

func (q *Queries) GetDataFileByID(ctx context.Context, id types.ID) (CoreDatafile, error) {
	row := q.DB.QueryRowContext(ctx, getDataFileByID, id)
	var i CoreDatafile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Path,
		&i.Size,
		&i.Hash,
		&i.Data,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getDataFileBySourceAndPath = `-- name: GetDataFileBySourceAndPath :one
SELECT 
    id, source_id, path, size, hash, data, created, updated
FROM core_datafile
WHERE source_id = $1 AND path = $2
`

type GetDataFileBySourceAndPathParams struct {
	SourceID types.ID `json:"source_id"`
	Path     string   `json:"path"`
}

func (q *Queries) GetDataFileBySourceAndPath(ctx context.Context, arg GetDataFileBySourceAndPathParams) (CoreDatafile, error) {
	row := q.DB.QueryRowContext(ctx, getDataFileBySourceAndPath, arg.SourceID, arg.Path)
	var i CoreDatafile
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Path,
		&i.Size,
		&i.Hash,
		&i.Data,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getDataFilesSummary = `-- name: GetDataFilesSummary :one
SELECT 
    COUNT(*)::int as total_files,
    COALESCE(SUM(size), 0)::bigint as total_size,
    COUNT(DISTINCT source_id)::int as total_sources
FROM core_datafile
`

type GetDataFilesSummaryRow struct {
	TotalFiles   int32 `json:"total_files"`
	TotalSize    int64 `json:"total_size"`
	TotalSources int32 `json:"total_sources"`
}

func (q *Queries) GetDataFilesSummary(ctx context.Context) (GetDataFilesSummaryRow, error) {
	row := q.DB.QueryRowContext(ctx, getDataFilesSummary)
	var i GetDataFilesSummaryRow
	err := row.Scan(&i.TotalFiles, &i.TotalSize, &i.TotalSources)
	return i, err
}

const getDataFilesWithHash = `-- name: GetDataFilesWithHash :many
SELECT 
    id, source_id, path, hash, created
FROM core_datafile
WHERE source_id = $1 AND hash = $2
`

type GetDataFilesWithHashParams struct {
	SourceID types.ID `json:"source_id"`
	Hash     string   `json:"hash"`
}

type GetDataFilesWithHashRow struct {
	ID       types.ID  `json:"id"`
	SourceID types.ID  `json:"source_id"`
	Path     string    `json:"path"`
	Hash     string    `json:"hash"`
	Created  time.Time `json:"created"`
}

func (q *Queries) GetDataFilesWithHash(ctx context.Context, arg GetDataFilesWithHashParams) ([]GetDataFilesWithHashRow, error) {
	rows, err := q.DB.QueryContext(ctx, getDataFilesWithHash, arg.SourceID, arg.Hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDataFilesWithHashRow{}
	for rows.Next() {
		var i GetDataFilesWithHashRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Path,
			&i.Hash,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataSourceByID = `-- name: GetDataSourceByID :one
SELECT 
    id, name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
FROM core_datasource
WHERE id = $1
`

func (q *Queries) GetDataSourceByID(ctx context.Context, id types.ID) (CoreDatasource, error) {
	row := q.DB.QueryRowContext(ctx, getDataSourceByID, id)
	var i CoreDatasource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.SourceUrl,
		&i.Status,
		&i.Enabled,
		&i.SyncInterval,
		&i.IgnoreRules,
		&i.Parameters,
		&i.LastSynced,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getDataSourceByName = `-- name: GetDataSourceByName :one
SELECT 
    id, name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
FROM core_datasource
WHERE name = $1
`

func (q *Queries) GetDataSourceByName(ctx context.Context, name string) (CoreDatasource, error) {
	row := q.DB.QueryRowContext(ctx, getDataSourceByName, name)
	var i CoreDatasource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.SourceUrl,
		&i.Status,
		&i.Enabled,
		&i.SyncInterval,
		&i.IgnoreRules,
		&i.Parameters,
		&i.LastSynced,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getDataSourcesByType = `-- name: GetDataSourcesByType :many
SELECT 
    id, name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
FROM core_datasource
WHERE type = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type GetDataSourcesByTypeParams struct {
	Type   string `json:"type"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetDataSourcesByType(ctx context.Context, arg GetDataSourcesByTypeParams) ([]CoreDatasource, error) {
	rows, err := q.DB.QueryContext(ctx, getDataSourcesByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDatasource{}
	for rows.Next() {
		var i CoreDatasource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.SourceUrl,
			&i.Status,
			&i.Enabled,
			&i.SyncInterval,
			&i.IgnoreRules,
			&i.Parameters,
			&i.LastSynced,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataSourcesDueForSync = `-- name: GetDataSourcesDueForSync :many
SELECT 
    id, name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
FROM core_datasource
WHERE enabled = TRUE 
  AND (last_synced IS NULL OR NOW() - last_synced >= sync_interval * INTERVAL '1 minute')
ORDER BY last_synced ASC NULLS FIRST
LIMIT $1
`

func (q *Queries) GetDataSourcesDueForSync(ctx context.Context, limit int32) ([]CoreDatasource, error) {
	rows, err := q.DB.QueryContext(ctx, getDataSourcesDueForSync, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDatasource{}
	for rows.Next() {
		var i CoreDatasource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.SourceUrl,
			&i.Status,
			&i.Enabled,
			&i.SyncInterval,
			&i.IgnoreRules,
			&i.Parameters,
			&i.LastSynced,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnabledDataSources = `-- name: GetEnabledDataSources :many

SELECT 
    id, name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
FROM core_datasource
WHERE enabled = TRUE
ORDER BY name
`

// ============================================================================
// Additional DataSource Queries
// ============================================================================
func (q *Queries) GetEnabledDataSources(ctx context.Context) ([]CoreDatasource, error) {
	rows, err := q.DB.QueryContext(ctx, getEnabledDataSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDatasource{}
	for rows.Next() {
		var i CoreDatasource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.SourceUrl,
			&i.Status,
			&i.Enabled,
			&i.SyncInterval,
			&i.IgnoreRules,
			&i.Parameters,
			&i.LastSynced,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJSONField = `-- name: GetJSONField :one

SELECT data->>$2 as value
FROM core_configrevision
WHERE id = $1
`

type GetJSONFieldParams struct {
	ID   types.ID        `json:"id"`
	Data json.RawMessage `json:"data"`
}

// ============================================================================
// JSON Helper Functions
// ============================================================================
func (q *Queries) GetJSONField(ctx context.Context, arg GetJSONFieldParams) (interface{}, error) {
	row := q.DB.QueryRowContext(ctx, getJSONField, arg.ID, arg.Data)
	var value interface{}
	err := row.Scan(&value)
	return value, err
}

const getJSONPath = `-- name: GetJSONPath :many
SELECT jsonb_path_query(data, $2::jsonpath)
FROM core_configrevision
WHERE id = $1
`

type GetJSONPathParams struct {
	ID      types.ID    `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) GetJSONPath(ctx context.Context, arg GetJSONPathParams) ([]json.RawMessage, error) {
	rows, err := q.DB.QueryContext(ctx, getJSONPath, arg.ID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var jsonb_path_query json.RawMessage
		if err := rows.Scan(&jsonb_path_query); err != nil {
			return nil, err
		}
		items = append(items, jsonb_path_query)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT 
    id, object_type, object_id, name, status, interval, scheduled_at,
    started_at, completed_at, queue_name, job_id, data, error, created, updated
FROM core_job
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id types.ID) (CoreJob, error) {
	row := q.DB.QueryRowContext(ctx, getJobByID, id)
	var i CoreJob
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Name,
		&i.Status,
		&i.Interval,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.QueueName,
		&i.JobID,
		&i.Data,
		&i.Error,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getJobStatistics = `-- name: GetJobStatistics :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'pending')::int as pending_count,
    COUNT(*) FILTER (WHERE status = 'running')::int as running_count,
    COUNT(*) FILTER (WHERE status = 'completed')::int as completed_count,
    COUNT(*) FILTER (WHERE status = 'failed')::int as failed_count,
    COUNT(*) FILTER (WHERE status = 'scheduled')::int as scheduled_count
FROM core_job
`

type GetJobStatisticsRow struct {
	PendingCount   int32 `json:"pending_count"`
	RunningCount   int32 `json:"running_count"`
	CompletedCount int32 `json:"completed_count"`
	FailedCount    int32 `json:"failed_count"`
	ScheduledCount int32 `json:"scheduled_count"`
}

func (q *Queries) GetJobStatistics(ctx context.Context) (GetJobStatisticsRow, error) {
	row := q.DB.QueryRowContext(ctx, getJobStatistics)
	var i GetJobStatisticsRow
	err := row.Scan(
		&i.PendingCount,
		&i.RunningCount,
		&i.CompletedCount,
		&i.FailedCount,
		&i.ScheduledCount,
	)
	return i, err
}

const getJobsByObjectTypeAndID = `-- name: GetJobsByObjectTypeAndID :many

SELECT 
    id, object_type, object_id, name, status, interval, scheduled_at,
    started_at, completed_at, queue_name, job_id, data, error, created, updated
FROM core_job
WHERE object_type = $1 AND object_id = $2
ORDER BY created DESC
LIMIT $3
`

type GetJobsByObjectTypeAndIDParams struct {
	ObjectType sql.NullString `json:"object_type"`
	ObjectID   uuid.NullUUID  `json:"object_id"`
	Limit      int32          `json:"limit"`
}

// ============================================================================
// Additional Job Queries
// ============================================================================
func (q *Queries) GetJobsByObjectTypeAndID(ctx context.Context, arg GetJobsByObjectTypeAndIDParams) ([]CoreJob, error) {
	rows, err := q.DB.QueryContext(ctx, getJobsByObjectTypeAndID, arg.ObjectType, arg.ObjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreJob{}
	for rows.Next() {
		var i CoreJob
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Name,
			&i.Status,
			&i.Interval,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.QueueName,
			&i.JobID,
			&i.Data,
			&i.Error,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectChangeByID = `-- name: GetObjectChangeByID :one
SELECT 
    id, time, user_id, request_id, action, changed_object_type, 
    changed_object_id, object_repr, object_data, related_object_type,
    related_object_id, related_object_repr
FROM core_objectchange
WHERE id = $1
`

func (q *Queries) GetObjectChangeByID(ctx context.Context, id types.ID) (CoreObjectchange, error) {
	row := q.DB.QueryRowContext(ctx, getObjectChangeByID, id)
	var i CoreObjectchange
	err := row.Scan(
		&i.ID,
		&i.Time,
		&i.UserID,
		&i.RequestID,
		&i.Action,
		&i.ChangedObjectType,
		&i.ChangedObjectID,
		&i.ObjectRepr,
		&i.ObjectData,
		&i.RelatedObjectType,
		&i.RelatedObjectID,
		&i.RelatedObjectRepr,
	)
	return i, err
}

const getObjectChangeCountByAction = `-- name: GetObjectChangeCountByAction :one
SELECT action, COUNT(*)::int as count
FROM core_objectchange
WHERE ($1::timestamp WITH TIME ZONE IS NULL OR time >= $1)
  AND ($2::timestamp WITH TIME ZONE IS NULL OR time <= $2)
GROUP BY action
`

type GetObjectChangeCountByActionParams struct {
	Column1 time.Time `json:"column_1"`
	Column2 time.Time `json:"column_2"`
}

type GetObjectChangeCountByActionRow struct {
	Action string `json:"action"`
	Count  int32  `json:"count"`
}

func (q *Queries) GetObjectChangeCountByAction(ctx context.Context, arg GetObjectChangeCountByActionParams) (GetObjectChangeCountByActionRow, error) {
	row := q.DB.QueryRowContext(ctx, getObjectChangeCountByAction, arg.Column1, arg.Column2)
	var i GetObjectChangeCountByActionRow
	err := row.Scan(&i.Action, &i.Count)
	return i, err
}

const getObjectChangesByObjectType = `-- name: GetObjectChangesByObjectType :many

SELECT 
    id, time, user_id, request_id, action, changed_object_type, 
    changed_object_id, object_repr, object_data, related_object_type,
    related_object_id, related_object_repr
FROM core_objectchange
WHERE changed_object_type = $1
ORDER BY time DESC
LIMIT $2 OFFSET $3
`

type GetObjectChangesByObjectTypeParams struct {
	ChangedObjectType string `json:"changed_object_type"`
	Limit             int32  `json:"limit"`
	Offset            int32  `json:"offset"`
}

// ============================================================================
// Additional ObjectChange Queries
// ============================================================================
func (q *Queries) GetObjectChangesByObjectType(ctx context.Context, arg GetObjectChangesByObjectTypeParams) ([]CoreObjectchange, error) {
	rows, err := q.DB.QueryContext(ctx, getObjectChangesByObjectType, arg.ChangedObjectType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreObjectchange{}
	for rows.Next() {
		var i CoreObjectchange
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.UserID,
			&i.RequestID,
			&i.Action,
			&i.ChangedObjectType,
			&i.ChangedObjectID,
			&i.ObjectRepr,
			&i.ObjectData,
			&i.RelatedObjectType,
			&i.RelatedObjectID,
			&i.RelatedObjectRepr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectTypeByAppAndModel = `-- name: GetObjectTypeByAppAndModel :one
SELECT 
    id, app_label, model, public, features, created, updated
FROM django_content_type
WHERE app_label = $1 AND model = $2
`

type GetObjectTypeByAppAndModelParams struct {
	AppLabel string `json:"app_label"`
	Model    string `json:"model"`
}

func (q *Queries) GetObjectTypeByAppAndModel(ctx context.Context, arg GetObjectTypeByAppAndModelParams) (DjangoContentType, error) {
	row := q.DB.QueryRowContext(ctx, getObjectTypeByAppAndModel, arg.AppLabel, arg.Model)
	var i DjangoContentType
	err := row.Scan(
		&i.ID,
		&i.AppLabel,
		&i.Model,
		&i.Public,
		&i.Features,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getObjectTypeByID = `-- name: GetObjectTypeByID :one
SELECT 
    id, app_label, model, public, features, created, updated
FROM django_content_type
WHERE id = $1
`

func (q *Queries) GetObjectTypeByID(ctx context.Context, id types.ID) (DjangoContentType, error) {
	row := q.DB.QueryRowContext(ctx, getObjectTypeByID, id)
	var i DjangoContentType
	err := row.Scan(
		&i.ID,
		&i.AppLabel,
		&i.Model,
		&i.Public,
		&i.Features,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getQueuedDataSources = `-- name: GetQueuedDataSources :many
SELECT 
    id, name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
FROM core_datasource
WHERE status = 'queued'
ORDER BY updated ASC
LIMIT $1
`

func (q *Queries) GetQueuedDataSources(ctx context.Context, limit int32) ([]CoreDatasource, error) {
	rows, err := q.DB.QueryContext(ctx, getQueuedDataSources, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDatasource{}
	for rows.Next() {
		var i CoreDatasource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.SourceUrl,
			&i.Status,
			&i.Enabled,
			&i.SyncInterval,
			&i.IgnoreRules,
			&i.Parameters,
			&i.LastSynced,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentObjectChanges = `-- name: GetRecentObjectChanges :many
SELECT 
    id, time, user_id, request_id, action, changed_object_type, 
    changed_object_id, object_repr, object_data, related_object_type,
    related_object_id, related_object_repr
FROM core_objectchange
WHERE changed_object_id = $1 AND changed_object_type = $2
ORDER BY time DESC
LIMIT $3
`

type GetRecentObjectChangesParams struct {
	ChangedObjectID   string `json:"changed_object_id"`
	ChangedObjectType string `json:"changed_object_type"`
	Limit             int32  `json:"limit"`
}

func (q *Queries) GetRecentObjectChanges(ctx context.Context, arg GetRecentObjectChangesParams) ([]CoreObjectchange, error) {
	rows, err := q.DB.QueryContext(ctx, getRecentObjectChanges, arg.ChangedObjectID, arg.ChangedObjectType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreObjectchange{}
	for rows.Next() {
		var i CoreObjectchange
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.UserID,
			&i.RequestID,
			&i.Action,
			&i.ChangedObjectType,
			&i.ChangedObjectID,
			&i.ObjectRepr,
			&i.ObjectData,
			&i.RelatedObjectType,
			&i.RelatedObjectID,
			&i.RelatedObjectRepr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunningJobs = `-- name: GetRunningJobs :many
SELECT 
    id, object_type, object_id, name, status, interval, scheduled_at,
    started_at, completed_at, queue_name, job_id, data, error, created, updated
FROM core_job
WHERE status IN ('running', 'started')
ORDER BY started_at ASC
`

func (q *Queries) GetRunningJobs(ctx context.Context) ([]CoreJob, error) {
	rows, err := q.DB.QueryContext(ctx, getRunningJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreJob{}
	for rows.Next() {
		var i CoreJob
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Name,
			&i.Status,
			&i.Interval,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.QueueName,
			&i.JobID,
			&i.Data,
			&i.Error,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledJobs = `-- name: GetScheduledJobs :many
SELECT 
    id, object_type, object_id, name, status, interval, scheduled_at,
    started_at, completed_at, queue_name, job_id, data, error, created, updated
FROM core_job
WHERE status = 'scheduled' AND scheduled_at <= $1
ORDER BY scheduled_at ASC
LIMIT $2
`

type GetScheduledJobsParams struct {
	ScheduledAt sql.NullTime `json:"scheduled_at"`
	Limit       int32        `json:"limit"`
}

func (q *Queries) GetScheduledJobs(ctx context.Context, arg GetScheduledJobsParams) ([]CoreJob, error) {
	rows, err := q.DB.QueryContext(ctx, getScheduledJobs, arg.ScheduledAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreJob{}
	for rows.Next() {
		var i CoreJob
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Name,
			&i.Status,
			&i.Interval,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.QueueName,
			&i.JobID,
			&i.Data,
			&i.Error,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigRevisions = `-- name: ListConfigRevisions :many
SELECT 
    id, created, active, comment, data
FROM core_configrevision
ORDER BY created DESC
LIMIT $1 OFFSET $2
`

type ListConfigRevisionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListConfigRevisions(ctx context.Context, arg ListConfigRevisionsParams) ([]CoreConfigrevision, error) {
	rows, err := q.DB.QueryContext(ctx, listConfigRevisions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreConfigrevision{}
	for rows.Next() {
		var i CoreConfigrevision
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Active,
			&i.Comment,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataFilesBySource = `-- name: ListDataFilesBySource :many
SELECT 
    id, source_id, path, size, hash, data, created, updated
FROM core_datafile
WHERE source_id = $1
ORDER BY path
LIMIT $2 OFFSET $3
`

type ListDataFilesBySourceParams struct {
	SourceID types.ID `json:"source_id"`
	Limit    int32    `json:"limit"`
	Offset   int32    `json:"offset"`
}

func (q *Queries) ListDataFilesBySource(ctx context.Context, arg ListDataFilesBySourceParams) ([]CoreDatafile, error) {
	rows, err := q.DB.QueryContext(ctx, listDataFilesBySource, arg.SourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDatafile{}
	for rows.Next() {
		var i CoreDatafile
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Path,
			&i.Size,
			&i.Hash,
			&i.Data,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataSources = `-- name: ListDataSources :many
SELECT 
    id, name, type, source_url, status, enabled, sync_interval,
    ignore_rules, parameters, last_synced, created, updated
FROM core_datasource
WHERE ($1 = '' OR status = $1)
  AND ($2::boolean IS NULL OR enabled = $2)
  AND ($3 = '' OR type = $3)
ORDER BY name
LIMIT $4 OFFSET $5
`

type ListDataSourcesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 bool        `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListDataSources(ctx context.Context, arg ListDataSourcesParams) ([]CoreDatasource, error) {
	rows, err := q.DB.QueryContext(ctx, listDataSources,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDatasource{}
	for rows.Next() {
		var i CoreDatasource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.SourceUrl,
			&i.Status,
			&i.Enabled,
			&i.SyncInterval,
			&i.IgnoreRules,
			&i.Parameters,
			&i.LastSynced,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT 
    id, object_type, object_id, name, status, interval, scheduled_at,
    started_at, completed_at, queue_name, job_id, data, error, created, updated
FROM core_job
WHERE ($1 = '' OR status = $1)
  AND ($2 = '' OR object_type = $2)
  AND ($3::uuid IS NULL OR object_id = $3)
  AND ($4 = '' OR queue_name = $4)
ORDER BY created DESC
LIMIT $5 OFFSET $6
`

type ListJobsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 types.ID    `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]CoreJob, error) {
	rows, err := q.DB.QueryContext(ctx, listJobs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreJob{}
	for rows.Next() {
		var i CoreJob
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Name,
			&i.Status,
			&i.Interval,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.QueueName,
			&i.JobID,
			&i.Data,
			&i.Error,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectChanges = `-- name: ListObjectChanges :many
SELECT 
    id, time, user_id, request_id, action, changed_object_type, 
    changed_object_id, object_repr, object_data, related_object_type,
    related_object_id, related_object_repr
FROM core_objectchange
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2 = '' OR action = $2)
  AND ($3 = '' OR changed_object_type = $3)
  AND ($4 = '' OR changed_object_id = $4)
  AND ($5::timestamp WITH TIME ZONE IS NULL OR time >= $5)
  AND ($6::timestamp WITH TIME ZONE IS NULL OR time <= $6)
ORDER BY time DESC
LIMIT $7 OFFSET $8
`

type ListObjectChangesParams struct {
	Column1 types.ID    `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 time.Time   `json:"column_5"`
	Column6 time.Time   `json:"column_6"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListObjectChanges(ctx context.Context, arg ListObjectChangesParams) ([]CoreObjectchange, error) {
	rows, err := q.DB.QueryContext(ctx, listObjectChanges,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreObjectchange{}
	for rows.Next() {
		var i CoreObjectchange
		if err := rows.Scan(
			&i.ID,
			&i.Time,
			&i.UserID,
			&i.RequestID,
			&i.Action,
			&i.ChangedObjectType,
			&i.ChangedObjectID,
			&i.ObjectRepr,
			&i.ObjectData,
			&i.RelatedObjectType,
			&i.RelatedObjectID,
			&i.RelatedObjectRepr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectTypes = `-- name: ListObjectTypes :many
SELECT 
    id, app_label, model, public, features, created, updated
FROM django_content_type
WHERE ($1 = '' OR app_label = $1)
  AND ($2 = '' OR model = $2)
  AND ($3::boolean IS NULL OR public = $3)
ORDER BY app_label, model
LIMIT $4 OFFSET $5
`

type ListObjectTypesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 bool        `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListObjectTypes(ctx context.Context, arg ListObjectTypesParams) ([]DjangoContentType, error) {
	rows, err := q.DB.QueryContext(ctx, listObjectTypes,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DjangoContentType{}
	for rows.Next() {
		var i DjangoContentType
		if err := rows.Scan(
			&i.ID,
			&i.AppLabel,
			&i.Model,
			&i.Public,
			&i.Features,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeJSONData = `-- name: MergeJSONData :execrows
UPDATE core_configrevision
SET data = COALESCE(data, '{}'::jsonb)::jsonb || $2::jsonb
WHERE id = $1
`

type MergeJSONDataParams struct {
	ID      types.ID        `json:"id"`
	Column2 json.RawMessage `json:"column_2"`
}

func (q *Queries) MergeJSONData(ctx context.Context, arg MergeJSONDataParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, mergeJSONData, arg.ID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryFailedJob = `-- name: RetryFailedJob :execrows
UPDATE core_job
SET status = 'pending', error = NULL, completed_at = NULL, updated = NOW()
WHERE id = $1 AND status IN ('failed', 'errored')
`

func (q *Queries) RetryFailedJob(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.DB.ExecContext(ctx, retryFailedJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchDataFilesByPathPattern = `-- name: SearchDataFilesByPathPattern :many

SELECT 
    id, source_id, path, size, hash, data, created, updated
FROM core_datafile
WHERE source_id = $1 AND path LIKE $2
ORDER BY path
LIMIT $3 OFFSET $4
`

type SearchDataFilesByPathPatternParams struct {
	SourceID types.ID `json:"source_id"`
	Path     string   `json:"path"`
	Limit    int32    `json:"limit"`
	Offset   int32    `json:"offset"`
}

// ============================================================================
// Additional DataFile Queries
// ============================================================================
func (q *Queries) SearchDataFilesByPathPattern(ctx context.Context, arg SearchDataFilesByPathPatternParams) ([]CoreDatafile, error) {
	rows, err := q.DB.QueryContext(ctx, searchDataFilesByPathPattern,
		arg.SourceID,
		arg.Path,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDatafile{}
	for rows.Next() {
		var i CoreDatafile
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Path,
			&i.Size,
			&i.Hash,
			&i.Data,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveConfigRevision = `-- name: SetActiveConfigRevision :execrows
UPDATE core_configrevision
SET active = FALSE
WHERE active = TRUE AND ID = $1
`

func (q *Queries) SetActiveConfigRevision(ctx context.Context, id types.ID) (int64, error) {
	result, err := q.DB.ExecContext(ctx, setActiveConfigRevision, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateConfigRevision = `-- name: UpdateConfigRevision :execrows
UPDATE core_configrevision
SET active = $2, comment = $3, data = $4
WHERE id = $1
`

type UpdateConfigRevisionParams struct {
	ID      types.ID        `json:"id"`
	Active  bool            `json:"active"`
	Comment sql.NullString  `json:"comment"`
	Data    json.RawMessage `json:"data"`
}

func (q *Queries) UpdateConfigRevision(ctx context.Context, arg UpdateConfigRevisionParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, updateConfigRevision,
		arg.ID,
		arg.Active,
		arg.Comment,
		arg.Data,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDataFile = `-- name: UpdateDataFile :execrows
UPDATE core_datafile
SET path = $2, size = $3, hash = $4, data = $5, updated = $6
WHERE id = $1
`

type UpdateDataFileParams struct {
	ID      types.ID              `json:"id"`
	Path    string                `json:"path"`
	Size    int64                 `json:"size"`
	Hash    string                `json:"hash"`
	Data    pqtype.NullRawMessage `json:"data"`
	Updated time.Time             `json:"updated"`
}

func (q *Queries) UpdateDataFile(ctx context.Context, arg UpdateDataFileParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, updateDataFile,
		arg.ID,
		arg.Path,
		arg.Size,
		arg.Hash,
		arg.Data,
		arg.Updated,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDataSource = `-- name: UpdateDataSource :execrows
UPDATE core_datasource
SET name = $2, type = $3, source_url = $4, status = $5, enabled = $6,
    sync_interval = $7, ignore_rules = $8, parameters = $9, 
    last_synced = $10, updated = $11
WHERE id = $1
`

type UpdateDataSourceParams struct {
	ID           types.ID              `json:"id"`
	Name         string                `json:"name"`
	Type         string                `json:"type"`
	SourceUrl    string                `json:"source_url"`
	Status       string                `json:"status"`
	Enabled      bool                  `json:"enabled"`
	SyncInterval int32                 `json:"sync_interval"`
	IgnoreRules  pqtype.NullRawMessage `json:"ignore_rules"`
	Parameters   pqtype.NullRawMessage `json:"parameters"`
	LastSynced   sql.NullTime          `json:"last_synced"`
	Updated      time.Time             `json:"updated"`
}

func (q *Queries) UpdateDataSource(ctx context.Context, arg UpdateDataSourceParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, updateDataSource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.SourceUrl,
		arg.Status,
		arg.Enabled,
		arg.SyncInterval,
		arg.IgnoreRules,
		arg.Parameters,
		arg.LastSynced,
		arg.Updated,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDataSourceLastSynced = `-- name: UpdateDataSourceLastSynced :execrows
UPDATE core_datasource
SET last_synced = $2, updated = NOW()
WHERE id = $1
`

type UpdateDataSourceLastSyncedParams struct {
	ID         types.ID     `json:"id"`
	LastSynced sql.NullTime `json:"last_synced"`
}

func (q *Queries) UpdateDataSourceLastSynced(ctx context.Context, arg UpdateDataSourceLastSyncedParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, updateDataSourceLastSynced, arg.ID, arg.LastSynced)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDataSourceStatus = `-- name: UpdateDataSourceStatus :execrows
UPDATE core_datasource
SET status = $2, last_synced = $3, updated = NOW()
WHERE id = $1
`

type UpdateDataSourceStatusParams struct {
	ID         types.ID     `json:"id"`
	Status     string       `json:"status"`
	LastSynced sql.NullTime `json:"last_synced"`
}

func (q *Queries) UpdateDataSourceStatus(ctx context.Context, arg UpdateDataSourceStatusParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, updateDataSourceStatus, arg.ID, arg.Status, arg.LastSynced)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateJSONField = `-- name: UpdateJSONField :execrows
UPDATE core_configrevision
SET data = jsonb_set(data::jsonb, $2, to_jsonb($3))
WHERE id = $1
`

type UpdateJSONFieldParams struct {
	ID      types.ID    `json:"id"`
	Path    interface{} `json:"path"`
	ToJsonb interface{} `json:"to_jsonb"`
}

func (q *Queries) UpdateJSONField(ctx context.Context, arg UpdateJSONFieldParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, updateJSONField, arg.ID, arg.Path, arg.ToJsonb)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateJob = `-- name: UpdateJob :execrows
UPDATE core_job
SET object_type = $2, object_id = $3, name = $4, status = $5, interval = $6,
    scheduled_at = $7, started_at = $8, completed_at = $9, queue_name = $10,
    job_id = $11, data = $12, error = $13, updated = $14
WHERE id = $1
`

type UpdateJobParams struct {
	ID          types.ID              `json:"id"`
	ObjectType  sql.NullString        `json:"object_type"`
	ObjectID    uuid.NullUUID         `json:"object_id"`
	Name        string                `json:"name"`
	Status      string                `json:"status"`
	Interval    sql.NullInt32         `json:"interval"`
	ScheduledAt sql.NullTime          `json:"scheduled_at"`
	StartedAt   sql.NullTime          `json:"started_at"`
	CompletedAt sql.NullTime          `json:"completed_at"`
	QueueName   sql.NullString        `json:"queue_name"`
	JobID       sql.NullString        `json:"job_id"`
	Data        pqtype.NullRawMessage `json:"data"`
	Error       sql.NullString        `json:"error"`
	Updated     time.Time             `json:"updated"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, updateJob,
		arg.ID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Name,
		arg.Status,
		arg.Interval,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.QueueName,
		arg.JobID,
		arg.Data,
		arg.Error,
		arg.Updated,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateJobStatus = `-- name: UpdateJobStatus :execrows
UPDATE core_job
SET status = $2, error = $3, completed_at = $4, updated = NOW()
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID          types.ID       `json:"id"`
	Status      string         `json:"status"`
	Error       sql.NullString `json:"error"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateObjectType = `-- name: UpdateObjectType :execrows
UPDATE django_content_type
SET app_label = $2, model = $3, public = $4, features = $5, updated = $6
WHERE id = $1
`

type UpdateObjectTypeParams struct {
	ID       types.ID              `json:"id"`
	AppLabel string                `json:"app_label"`
	Model    string                `json:"model"`
	Public   bool                  `json:"public"`
	Features pqtype.NullRawMessage `json:"features"`
	Updated  time.Time             `json:"updated"`
}

func (q *Queries) UpdateObjectType(ctx context.Context, arg UpdateObjectTypeParams) (int64, error) {
	result, err := q.DB.ExecContext(ctx, updateObjectType,
		arg.ID,
		arg.AppLabel,
		arg.Model,
		arg.Public,
		arg.Features,
		arg.Updated,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
