// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dcimdb

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"netbox_go/pkg/types"
)

type DcimCableStatus string

const (
	DcimCableStatusConnected       DcimCableStatus = "connected"
	DcimCableStatusPlanned         DcimCableStatus = "planned"
	DcimCableStatusDecommissioning DcimCableStatus = "decommissioning"
	DcimCableStatusFailed          DcimCableStatus = "failed"
)

func (e *DcimCableStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimCableStatus(s)
	case string:
		*e = DcimCableStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimCableStatus: %T", src)
	}
	return nil
}

type NullDcimCableStatus struct {
	DcimCableStatus DcimCableStatus `json:"dcim_cable_status"`
	Valid           bool            `json:"valid"` // Valid is true if DcimCableStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimCableStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DcimCableStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimCableStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimCableStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimCableStatus), nil
}

type DcimCableType string

const (
	DcimCableTypeCat3               DcimCableType = "cat3"
	DcimCableTypeCat5               DcimCableType = "cat5"
	DcimCableTypeCat5e              DcimCableType = "cat5e"
	DcimCableTypeCat6               DcimCableType = "cat6"
	DcimCableTypeCat6a              DcimCableType = "cat6a"
	DcimCableTypeCat7               DcimCableType = "cat7"
	DcimCableTypeCat8               DcimCableType = "cat8"
	DcimCableTypeDac                DcimCableType = "dac"
	DcimCableTypeMrj21              DcimCableType = "mrj21"
	DcimCableTypeMtp                DcimCableType = "mtp"
	DcimCableTypeMultimodeFiber     DcimCableType = "multimode-fiber"
	DcimCableTypeMultimodeFiberOm1  DcimCableType = "multimode-fiber-om1"
	DcimCableTypeMultimodeFiberOm2  DcimCableType = "multimode-fiber-om2"
	DcimCableTypeMultimodeFiberOm3  DcimCableType = "multimode-fiber-om3"
	DcimCableTypeMultimodeFiberOm4  DcimCableType = "multimode-fiber-om4"
	DcimCableTypeMultimodeFiberOm5  DcimCableType = "multimode-fiber-om5"
	DcimCableTypeSinglemodeFiber    DcimCableType = "singlemode-fiber"
	DcimCableTypeSinglemodeFiberOs1 DcimCableType = "singlemode-fiber-os1"
	DcimCableTypeSinglemodeFiberOs2 DcimCableType = "singlemode-fiber-os2"
	DcimCableTypeCoaxial            DcimCableType = "coaxial"
	DcimCableTypePower              DcimCableType = "power"
)

func (e *DcimCableType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimCableType(s)
	case string:
		*e = DcimCableType(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimCableType: %T", src)
	}
	return nil
}

type NullDcimCableType struct {
	DcimCableType DcimCableType `json:"dcim_cable_type"`
	Valid         bool          `json:"valid"` // Valid is true if DcimCableType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimCableType) Scan(value interface{}) error {
	if value == nil {
		ns.DcimCableType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimCableType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimCableType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimCableType), nil
}

type DcimLocationStatus string

const (
	DcimLocationStatusPlanned DcimLocationStatus = "planned"
	DcimLocationStatusStaging DcimLocationStatus = "staging"
	DcimLocationStatusActive  DcimLocationStatus = "active"
	DcimLocationStatusRetired DcimLocationStatus = "retired"
)

func (e *DcimLocationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimLocationStatus(s)
	case string:
		*e = DcimLocationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimLocationStatus: %T", src)
	}
	return nil
}

type NullDcimLocationStatus struct {
	DcimLocationStatus DcimLocationStatus `json:"dcim_location_status"`
	Valid              bool               `json:"valid"` // Valid is true if DcimLocationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimLocationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DcimLocationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimLocationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimLocationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimLocationStatus), nil
}

type DcimPhaseType string

const (
	DcimPhaseType1Phase DcimPhaseType = "1-phase"
	DcimPhaseType3Phase DcimPhaseType = "3-phase"
)

func (e *DcimPhaseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimPhaseType(s)
	case string:
		*e = DcimPhaseType(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimPhaseType: %T", src)
	}
	return nil
}

type NullDcimPhaseType struct {
	DcimPhaseType DcimPhaseType `json:"dcim_phase_type"`
	Valid         bool          `json:"valid"` // Valid is true if DcimPhaseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimPhaseType) Scan(value interface{}) error {
	if value == nil {
		ns.DcimPhaseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimPhaseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimPhaseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimPhaseType), nil
}

type DcimPowerFeedStatus string

const (
	DcimPowerFeedStatusOffline DcimPowerFeedStatus = "offline"
	DcimPowerFeedStatusActive  DcimPowerFeedStatus = "active"
	DcimPowerFeedStatusPlanned DcimPowerFeedStatus = "planned"
	DcimPowerFeedStatusFailed  DcimPowerFeedStatus = "failed"
)

func (e *DcimPowerFeedStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimPowerFeedStatus(s)
	case string:
		*e = DcimPowerFeedStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimPowerFeedStatus: %T", src)
	}
	return nil
}

type NullDcimPowerFeedStatus struct {
	DcimPowerFeedStatus DcimPowerFeedStatus `json:"dcim_power_feed_status"`
	Valid               bool                `json:"valid"` // Valid is true if DcimPowerFeedStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimPowerFeedStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DcimPowerFeedStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimPowerFeedStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimPowerFeedStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimPowerFeedStatus), nil
}

type DcimPowerFeedType string

const (
	DcimPowerFeedTypePrimary   DcimPowerFeedType = "primary"
	DcimPowerFeedTypeRedundant DcimPowerFeedType = "redundant"
)

func (e *DcimPowerFeedType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimPowerFeedType(s)
	case string:
		*e = DcimPowerFeedType(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimPowerFeedType: %T", src)
	}
	return nil
}

type NullDcimPowerFeedType struct {
	DcimPowerFeedType DcimPowerFeedType `json:"dcim_power_feed_type"`
	Valid             bool              `json:"valid"` // Valid is true if DcimPowerFeedType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimPowerFeedType) Scan(value interface{}) error {
	if value == nil {
		ns.DcimPowerFeedType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimPowerFeedType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimPowerFeedType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimPowerFeedType), nil
}

type DcimPowerSupply string

const (
	DcimPowerSupplyAc DcimPowerSupply = "ac"
	DcimPowerSupplyDc DcimPowerSupply = "dc"
)

func (e *DcimPowerSupply) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimPowerSupply(s)
	case string:
		*e = DcimPowerSupply(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimPowerSupply: %T", src)
	}
	return nil
}

type NullDcimPowerSupply struct {
	DcimPowerSupply DcimPowerSupply `json:"dcim_power_supply"`
	Valid           bool            `json:"valid"` // Valid is true if DcimPowerSupply is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimPowerSupply) Scan(value interface{}) error {
	if value == nil {
		ns.DcimPowerSupply, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimPowerSupply.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimPowerSupply) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimPowerSupply), nil
}

type DcimPowerUnit string

const (
	DcimPowerUnitW  DcimPowerUnit = "w"
	DcimPowerUnitKw DcimPowerUnit = "kw"
)

func (e *DcimPowerUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimPowerUnit(s)
	case string:
		*e = DcimPowerUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimPowerUnit: %T", src)
	}
	return nil
}

type NullDcimPowerUnit struct {
	DcimPowerUnit DcimPowerUnit `json:"dcim_power_unit"`
	Valid         bool          `json:"valid"` // Valid is true if DcimPowerUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimPowerUnit) Scan(value interface{}) error {
	if value == nil {
		ns.DcimPowerUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimPowerUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimPowerUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimPowerUnit), nil
}

type DcimRackDimensionUnit string

const (
	DcimRackDimensionUnitMm DcimRackDimensionUnit = "mm"
	DcimRackDimensionUnitIn DcimRackDimensionUnit = "in"
)

func (e *DcimRackDimensionUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimRackDimensionUnit(s)
	case string:
		*e = DcimRackDimensionUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimRackDimensionUnit: %T", src)
	}
	return nil
}

type NullDcimRackDimensionUnit struct {
	DcimRackDimensionUnit DcimRackDimensionUnit `json:"dcim_rack_dimension_unit"`
	Valid                 bool                  `json:"valid"` // Valid is true if DcimRackDimensionUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimRackDimensionUnit) Scan(value interface{}) error {
	if value == nil {
		ns.DcimRackDimensionUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimRackDimensionUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimRackDimensionUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimRackDimensionUnit), nil
}

type DcimRackStatus string

const (
	DcimRackStatusReserved   DcimRackStatus = "reserved"
	DcimRackStatusAvailable  DcimRackStatus = "available"
	DcimRackStatusPlanned    DcimRackStatus = "planned"
	DcimRackStatusActive     DcimRackStatus = "active"
	DcimRackStatusDeprecated DcimRackStatus = "deprecated"
)

func (e *DcimRackStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimRackStatus(s)
	case string:
		*e = DcimRackStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimRackStatus: %T", src)
	}
	return nil
}

type NullDcimRackStatus struct {
	DcimRackStatus DcimRackStatus `json:"dcim_rack_status"`
	Valid          bool           `json:"valid"` // Valid is true if DcimRackStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimRackStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DcimRackStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimRackStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimRackStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimRackStatus), nil
}

type DcimRackTypeFormFactor string

const (
	DcimRackTypeFormFactorWallframe    DcimRackTypeFormFactor = "wallframe"
	DcimRackTypeFormFactorWallcabinet  DcimRackTypeFormFactor = "wallcabinet"
	DcimRackTypeFormFactor4postframe   DcimRackTypeFormFactor = "4postframe"
	DcimRackTypeFormFactor4postcabinet DcimRackTypeFormFactor = "4postcabinet"
	DcimRackTypeFormFactor2postframe   DcimRackTypeFormFactor = "2postframe"
	DcimRackTypeFormFactor2postcabinet DcimRackTypeFormFactor = "2postcabinet"
)

func (e *DcimRackTypeFormFactor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimRackTypeFormFactor(s)
	case string:
		*e = DcimRackTypeFormFactor(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimRackTypeFormFactor: %T", src)
	}
	return nil
}

type NullDcimRackTypeFormFactor struct {
	DcimRackTypeFormFactor DcimRackTypeFormFactor `json:"dcim_rack_type_form_factor"`
	Valid                  bool                   `json:"valid"` // Valid is true if DcimRackTypeFormFactor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimRackTypeFormFactor) Scan(value interface{}) error {
	if value == nil {
		ns.DcimRackTypeFormFactor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimRackTypeFormFactor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimRackTypeFormFactor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimRackTypeFormFactor), nil
}

type DcimSiteStatus string

const (
	DcimSiteStatusPlanned DcimSiteStatus = "planned"
	DcimSiteStatusStaging DcimSiteStatus = "staging"
	DcimSiteStatusActive  DcimSiteStatus = "active"
	DcimSiteStatusRetired DcimSiteStatus = "retired"
)

func (e *DcimSiteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DcimSiteStatus(s)
	case string:
		*e = DcimSiteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DcimSiteStatus: %T", src)
	}
	return nil
}

type NullDcimSiteStatus struct {
	DcimSiteStatus DcimSiteStatus `json:"dcim_site_status"`
	Valid          bool           `json:"valid"` // Valid is true if DcimSiteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDcimSiteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DcimSiteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DcimSiteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDcimSiteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DcimSiteStatus), nil
}

type DcimCable struct {
	ID          types.ID            `json:"id"`
	Type        DcimCableType       `json:"type"`
	Status      NullDcimCableStatus `json:"status"`
	Label       sql.NullString      `json:"label"`
	Color       sql.NullString      `json:"color"`
	Length      sql.NullInt32       `json:"length"`
	LengthUnit  sql.NullString      `json:"length_unit"`
	Description sql.NullString      `json:"description"`
	TenantID    uuid.NullUUID       `json:"tenant_id"`
	Created     sql.NullTime        `json:"created"`
	Updated     sql.NullTime        `json:"updated"`
	DeletedAt   sql.NullTime        `json:"deleted_at"`
}

type DcimCableTermination struct {
	ID              types.ID     `json:"id"`
	CableID         types.ID     `json:"cable_id"`
	TerminationType string       `json:"termination_type"`
	TerminationID   types.ID     `json:"termination_id"`
	CableEnd        string       `json:"cable_end"`
	Created         sql.NullTime `json:"created"`
}

type DcimLocation struct {
	ID          types.ID               `json:"id"`
	Name        string                 `json:"name"`
	Slug        string                 `json:"slug"`
	SiteID      types.ID               `json:"site_id"`
	Status      NullDcimLocationStatus `json:"status"`
	ParentID    uuid.NullUUID          `json:"parent_id"`
	TenantID    uuid.NullUUID          `json:"tenant_id"`
	Facility    sql.NullString         `json:"facility"`
	Description sql.NullString         `json:"description"`
	Comments    sql.NullString         `json:"comments"`
	Created     sql.NullTime           `json:"created"`
	Updated     sql.NullTime           `json:"updated"`
	DeletedAt   sql.NullTime           `json:"deleted_at"`
}

type DcimPowerFeed struct {
	ID             types.ID                `json:"id"`
	PowerPanelID   types.ID                `json:"power_panel_id"`
	RackID         uuid.NullUUID           `json:"rack_id"`
	Name           string                  `json:"name"`
	Status         NullDcimPowerFeedStatus `json:"status"`
	Type           NullDcimPowerFeedType   `json:"type"`
	Supply         NullDcimPowerSupply     `json:"supply"`
	Phase          NullDcimPhaseType       `json:"phase"`
	Voltage        int32                   `json:"voltage"`
	Amperage       int32                   `json:"amperage"`
	MaxUtilization sql.NullInt32           `json:"max_utilization"`
	AvailablePower sql.NullInt32           `json:"available_power"`
	Unit           NullDcimPowerUnit       `json:"unit"`
	Description    sql.NullString          `json:"description"`
	CableID        uuid.NullUUID           `json:"cable_id"`
	CableEnd       sql.NullString          `json:"cable_end"`
	Created        sql.NullTime            `json:"created"`
	Updated        sql.NullTime            `json:"updated"`
	DeletedAt      sql.NullTime            `json:"deleted_at"`
}

type DcimPowerPanel struct {
	ID          types.ID       `json:"id"`
	SiteID      types.ID       `json:"site_id"`
	LocationID  uuid.NullUUID  `json:"location_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type DcimRack struct {
	ID            types.ID                   `json:"id"`
	Name          string                     `json:"name"`
	FacilityID    sql.NullString             `json:"facility_id"`
	SiteID        types.ID                   `json:"site_id"`
	LocationID    uuid.NullUUID              `json:"location_id"`
	TenantID      uuid.NullUUID              `json:"tenant_id"`
	Status        NullDcimRackStatus         `json:"status"`
	RoleID        uuid.NullUUID              `json:"role_id"`
	RackTypeID    uuid.NullUUID              `json:"rack_type_id"`
	FormFactor    NullDcimRackTypeFormFactor `json:"form_factor"`
	Width         int16                      `json:"width"`
	Serial        sql.NullString             `json:"serial"`
	AssetTag      sql.NullString             `json:"asset_tag"`
	Airflow       sql.NullString             `json:"airflow"`
	UHeight       int16                      `json:"u_height"`
	StartingUnit  sql.NullInt16              `json:"starting_unit"`
	DescUnits     sql.NullBool               `json:"desc_units"`
	OuterWidth    sql.NullInt16              `json:"outer_width"`
	OuterHeight   sql.NullInt16              `json:"outer_height"`
	OuterDepth    sql.NullInt16              `json:"outer_depth"`
	OuterUnit     NullDcimRackDimensionUnit  `json:"outer_unit"`
	MountingDepth sql.NullInt16              `json:"mounting_depth"`
	Weight        sql.NullInt32              `json:"weight"`
	MaxWeight     sql.NullInt32              `json:"max_weight"`
	WeightUnit    sql.NullString             `json:"weight_unit"`
	Description   sql.NullString             `json:"description"`
	Comments      sql.NullString             `json:"comments"`
	Created       sql.NullTime               `json:"created"`
	Updated       sql.NullTime               `json:"updated"`
	DeletedAt     sql.NullTime               `json:"deleted_at"`
}

type DcimRackReservation struct {
	ID          types.ID       `json:"id"`
	RackID      types.ID       `json:"rack_id"`
	UserID      types.ID       `json:"user_id"`
	TenantID    uuid.NullUUID  `json:"tenant_id"`
	Units       []int16        `json:"units"`
	Description sql.NullString `json:"description"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
}

type DcimRackType struct {
	ID             types.ID                  `json:"id"`
	ManufacturerID types.ID                  `json:"manufacturer_id"`
	Model          string                    `json:"model"`
	Slug           string                    `json:"slug"`
	Description    sql.NullString            `json:"description"`
	FormFactor     DcimRackTypeFormFactor    `json:"form_factor"`
	Width          int16                     `json:"width"`
	UHeight        int16                     `json:"u_height"`
	StartingUnit   sql.NullInt16             `json:"starting_unit"`
	DescUnits      sql.NullBool              `json:"desc_units"`
	OuterWidth     sql.NullInt16             `json:"outer_width"`
	OuterHeight    sql.NullInt16             `json:"outer_height"`
	OuterDepth     sql.NullInt16             `json:"outer_depth"`
	OuterUnit      NullDcimRackDimensionUnit `json:"outer_unit"`
	MountingDepth  sql.NullInt16             `json:"mounting_depth"`
	Weight         sql.NullInt32             `json:"weight"`
	MaxWeight      sql.NullInt32             `json:"max_weight"`
	WeightUnit     sql.NullString            `json:"weight_unit"`
	Created        sql.NullTime              `json:"created"`
	Updated        sql.NullTime              `json:"updated"`
}

type DcimRegion struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type DcimSite struct {
	ID              types.ID           `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Status          NullDcimSiteStatus `json:"status"`
	RegionID        uuid.NullUUID      `json:"region_id"`
	GroupID         uuid.NullUUID      `json:"group_id"`
	TenantID        uuid.NullUUID      `json:"tenant_id"`
	Facility        sql.NullString     `json:"facility"`
	AsnIds          []types.ID         `json:"asn_ids"`
	TimeZone        sql.NullString     `json:"time_zone"`
	PhysicalAddress sql.NullString     `json:"physical_address"`
	ShippingAddress sql.NullString     `json:"shipping_address"`
	Latitude        sql.NullString     `json:"latitude"`
	Longitude       sql.NullString     `json:"longitude"`
	Description     sql.NullString     `json:"description"`
	Comments        sql.NullString     `json:"comments"`
	Created         sql.NullTime       `json:"created"`
	Updated         sql.NullTime       `json:"updated"`
	DeletedAt       sql.NullTime       `json:"deleted_at"`
}

type DcimSiteGroup struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Created     sql.NullTime   `json:"created"`
	Updated     sql.NullTime   `json:"updated"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}
