// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dcimdb

import (
	"context"
)

const listRegions = `-- name: ListRegions :many
SELECT id, name, slug, description, parent_id, created, updated, deleted_at FROM dcim_regions ORDER BY name LIMIT $1 OFFSET $2
`

type ListRegionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// DCIM queries stub
func (q *Queries) ListRegions(ctx context.Context, arg ListRegionsParams) ([]DcimRegion, error) {
	rows, err := q.db.QueryContext(ctx, listRegions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DcimRegion{}
	for rows.Next() {
		var i DcimRegion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.Created,
			&i.Updated,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
