// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tasksdb

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"netbox_go/pkg/types"
)

type AssigneeTypeEnum string

const (
	AssigneeTypeEnumUser  AssigneeTypeEnum = "user"
	AssigneeTypeEnumGroup AssigneeTypeEnum = "group"
)

func (e *AssigneeTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssigneeTypeEnum(s)
	case string:
		*e = AssigneeTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AssigneeTypeEnum: %T", src)
	}
	return nil
}

type NullAssigneeTypeEnum struct {
	AssigneeTypeEnum AssigneeTypeEnum `json:"assignee_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if AssigneeTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssigneeTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AssigneeTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssigneeTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssigneeTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssigneeTypeEnum), nil
}

type GroupTypeEnum string

const (
	GroupTypeEnumAssignee GroupTypeEnum = "assignee"
	GroupTypeEnumReviewer GroupTypeEnum = "reviewer"
)

func (e *GroupTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupTypeEnum(s)
	case string:
		*e = GroupTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupTypeEnum: %T", src)
	}
	return nil
}

type NullGroupTypeEnum struct {
	GroupTypeEnum GroupTypeEnum `json:"group_type_enum"`
	Valid         bool          `json:"valid"` // Valid is true if GroupTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GroupTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupTypeEnum), nil
}

type TaskRoleEnum string

const (
	TaskRoleEnumCreator  TaskRoleEnum = "creator"
	TaskRoleEnumAssignee TaskRoleEnum = "assignee"
	TaskRoleEnumReviewer TaskRoleEnum = "reviewer"
)

func (e *TaskRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskRoleEnum(s)
	case string:
		*e = TaskRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskRoleEnum: %T", src)
	}
	return nil
}

type NullTaskRoleEnum struct {
	TaskRoleEnum TaskRoleEnum `json:"task_role_enum"`
	Valid        bool         `json:"valid"` // Valid is true if TaskRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TaskRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskRoleEnum), nil
}

type TaskStatusEnum string

const (
	TaskStatusEnumDraft       TaskStatusEnum = "draft"
	TaskStatusEnumAssigned    TaskStatusEnum = "assigned"
	TaskStatusEnumInProgress  TaskStatusEnum = "in_progress"
	TaskStatusEnumCompleted   TaskStatusEnum = "completed"
	TaskStatusEnumUnderReview TaskStatusEnum = "under_review"
	TaskStatusEnumApproved    TaskStatusEnum = "approved"
	TaskStatusEnumRejected    TaskStatusEnum = "rejected"
	TaskStatusEnumCancelled   TaskStatusEnum = "cancelled"
)

func (e *TaskStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatusEnum(s)
	case string:
		*e = TaskStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatusEnum: %T", src)
	}
	return nil
}

type NullTaskStatusEnum struct {
	TaskStatusEnum TaskStatusEnum `json:"task_status_enum"`
	Valid          bool           `json:"valid"` // Valid is true if TaskStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatusEnum), nil
}

// Группы пользователей (ответственные или проверяющие)
type TasksGroup struct {
	ID   types.ID `json:"id"`
	Name string   `json:"name"`
	// Тип группы: assignee (ответственные) или reviewer (проверяющие)
	Type        GroupTypeEnum  `json:"type"`
	Description sql.NullString `json:"description"`
	// Начало смены для групп-смен
	ShiftStart sql.NullTime `json:"shift_start"`
	// Конец смены для групп-смен
	ShiftEnd sql.NullTime `json:"shift_end"`
	// Дни недели работы группы
	WorkDays []string  `json:"work_days"`
	Created  time.Time `json:"created"`
	Updated  time.Time `json:"updated"`
}

// Участники групп
type TasksGroupMember struct {
	ID      types.ID  `json:"id"`
	GroupID types.ID  `json:"group_id"`
	UserID  types.ID  `json:"user_id"`
	Created time.Time `json:"created"`
	AddedBy types.ID  `json:"added_by"`
}

// Компетенции групп (какие виды работ может выполнять группа)
type TasksGroupWorktype struct {
	ID         types.ID  `json:"id"`
	GroupID    types.ID  `json:"group_id"`
	WorkTypeID types.ID  `json:"work_type_id"`
	Created    time.Time `json:"created"`
	AddedBy    types.ID  `json:"added_by"`
}

// Задачи
type TasksTask struct {
	ID          types.ID       `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	WorkTypeID  types.ID       `json:"work_type_id"`
	// Статус задачи
	Status TaskStatusEnum `json:"status"`
	// Приоритет задачи (1-5, где 5 - наивысший)
	Priority      int32          `json:"priority"`
	CreatedByID   types.ID       `json:"created_by_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DueDate       sql.NullTime   `json:"due_date"`
	CompletedAt   sql.NullTime   `json:"completed_at"`
	ReviewedAt    sql.NullTime   `json:"reviewed_at"`
	ReviewComment sql.NullString `json:"review_comment"`
}

// Назначения ролей в задачах (кто создатель, ответственный, проверяющий)
type TasksTaskAssignment struct {
	ID     types.ID `json:"id"`
	TaskID types.ID `json:"task_id"`
	// Роль в задаче: creator, assignee, reviewer
	Role TaskRoleEnum `json:"role"`
	// Тип назначения: user или group
	AssigneeType AssigneeTypeEnum `json:"assignee_type"`
	UserID       uuid.NullUUID    `json:"user_id"`
	GroupID      uuid.NullUUID    `json:"group_id"`
	CreatedAt    time.Time        `json:"created_at"`
	CreatedBy    types.ID         `json:"created_by"`
	// Фактический исполнитель (если задача назначена группе)
	ActualExecutorID uuid.NullUUID `json:"actual_executor_id"`
}

// Вложения к задачам
type TasksTaskAttachment struct {
	ID         types.ID       `json:"id"`
	TaskID     types.ID       `json:"task_id"`
	FileName   string         `json:"file_name"`
	FileSize   int64          `json:"file_size"`
	FileType   sql.NullString `json:"file_type"`
	UploadedBy types.ID       `json:"uploaded_by"`
	UploadedAt time.Time      `json:"uploaded_at"`
}

// Комментарии к задачам
type TasksTaskComment struct {
	ID        types.ID  `json:"id"`
	TaskID    types.ID  `json:"task_id"`
	AuthorID  types.ID  `json:"author_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Справочник видов работ
type TasksWorktype struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Created     time.Time      `json:"created"`
	Updated     time.Time      `json:"updated"`
}
