// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package tasksdb

import (
	"context"
)

const listWorkTypes = `-- name: ListWorkTypes :many
SELECT id, name, description, created, updated FROM tasks_worktype ORDER BY name LIMIT $1 OFFSET $2
`

type ListWorkTypesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Tasks queries stub
func (q *Queries) ListWorkTypes(ctx context.Context, arg ListWorkTypesParams) ([]TasksWorktype, error) {
	rows, err := q.db.QueryContext(ctx, listWorkTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TasksWorktype{}
	for rows.Next() {
		var i TasksWorktype
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
