// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package extrasdb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
	"netbox_go/pkg/types"
)

type ExtrasBookmark struct {
	ID         types.ID  `json:"id"`
	ObjectType string    `json:"object_type"`
	ObjectID   int64     `json:"object_id"`
	UserID     types.ID  `json:"user_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type ExtrasCustomlink struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Enabled     bool           `json:"enabled"`
	LinkText    string         `json:"link_text"`
	LinkUrl     string         `json:"link_url"`
	Weight      int16          `json:"weight"`
	GroupName   sql.NullString `json:"group_name"`
	ButtonClass string         `json:"button_class"`
	NewWindow   bool           `json:"new_window"`
	OwnerID     uuid.NullUUID  `json:"owner_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ExtrasCustomlinkObjectType struct {
	CustomLinkID types.ID `json:"custom_link_id"`
	ContentType  string   `json:"content_type"`
}

type ExtrasEventrule struct {
	ID               types.ID              `json:"id"`
	Name             string                `json:"name"`
	Description      sql.NullString        `json:"description"`
	EventTypes       []string              `json:"event_types"`
	Enabled          bool                  `json:"enabled"`
	Conditions       pqtype.NullRawMessage `json:"conditions"`
	ActionType       string                `json:"action_type"`
	ActionObjectType string                `json:"action_object_type"`
	ActionObjectID   sql.NullInt64         `json:"action_object_id"`
	ActionData       pqtype.NullRawMessage `json:"action_data"`
	Comments         sql.NullString        `json:"comments"`
	OwnerID          uuid.NullUUID         `json:"owner_id"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        time.Time             `json:"updated_at"`
}

type ExtrasEventruleObjectType struct {
	EventRuleID types.ID `json:"event_rule_id"`
	ContentType string   `json:"content_type"`
}

type ExtrasExporttemplate struct {
	ID            types.ID       `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	TemplateCode  string         `json:"template_code"`
	MimeType      string         `json:"mime_type"`
	FileName      string         `json:"file_name"`
	FileExtension string         `json:"file_extension"`
	AsAttachment  bool           `json:"as_attachment"`
	OwnerID       uuid.NullUUID  `json:"owner_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type ExtrasExporttemplateObjectType struct {
	ExportTemplateID types.ID `json:"export_template_id"`
	ContentType      string   `json:"content_type"`
}

type ExtrasImageattachment struct {
	ID          types.ID       `json:"id"`
	ObjectType  string         `json:"object_type"`
	ObjectID    int64          `json:"object_id"`
	Image       string         `json:"image"`
	ImageHeight int16          `json:"image_height"`
	ImageWidth  int16          `json:"image_width"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ExtrasJournalentry struct {
	ID                 types.ID      `json:"id"`
	AssignedObjectType string        `json:"assigned_object_type"`
	AssignedObjectID   int64         `json:"assigned_object_id"`
	CreatedBy          uuid.NullUUID `json:"created_by"`
	Kind               string        `json:"kind"`
	Comments           string        `json:"comments"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
}

type ExtrasSavedfilter struct {
	ID          types.ID        `json:"id"`
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Description sql.NullString  `json:"description"`
	UserID      uuid.NullUUID   `json:"user_id"`
	Weight      int16           `json:"weight"`
	Enabled     bool            `json:"enabled"`
	Shared      bool            `json:"shared"`
	Parameters  json.RawMessage `json:"parameters"`
	OwnerID     uuid.NullUUID   `json:"owner_id"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type ExtrasSavedfilterObjectType struct {
	SavedFilterID types.ID `json:"saved_filter_id"`
	ContentType   string   `json:"content_type"`
}

type ExtrasTableconfig struct {
	ID          types.ID       `json:"id"`
	ObjectType  string         `json:"object_type"`
	Table       string         `json:"table"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      uuid.NullUUID  `json:"user_id"`
	Weight      int16          `json:"weight"`
	Enabled     bool           `json:"enabled"`
	Shared      bool           `json:"shared"`
	Columns     []string       `json:"columns"`
	Ordering    []string       `json:"ordering"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ExtrasWebhook struct {
	ID                types.ID       `json:"id"`
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	PayloadUrl        string         `json:"payload_url"`
	HttpMethod        string         `json:"http_method"`
	HttpContentType   string         `json:"http_content_type"`
	AdditionalHeaders sql.NullString `json:"additional_headers"`
	BodyTemplate      sql.NullString `json:"body_template"`
	Secret            sql.NullString `json:"secret"`
	SslVerification   bool           `json:"ssl_verification"`
	CaFilePath        sql.NullString `json:"ca_file_path"`
	OwnerID           uuid.NullUUID  `json:"owner_id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}
