// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package extrasdb

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
	"netbox_go/pkg/types"
)

const createBookmark = `-- name: CreateBookmark :exec
INSERT INTO extras_bookmark (id, object_type, object_id, user_id)
VALUES ($1, $2, $3, $4)
`

type CreateBookmarkParams struct {
	ID         types.ID `json:"id"`
	ObjectType string   `json:"object_type"`
	ObjectID   int64    `json:"object_id"`
	UserID     types.ID `json:"user_id"`
}

// Bookmark
// desc: Create a new bookmark
func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, createBookmark,
		arg.ID,
		arg.ObjectType,
		arg.ObjectID,
		arg.UserID,
	)
	return err
}

const createCustomLink = `-- name: CreateCustomLink :exec
INSERT INTO extras_customlink (id, name, enabled, link_text, link_url, weight, group_name, button_class, new_window, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateCustomLinkParams struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Enabled     bool           `json:"enabled"`
	LinkText    string         `json:"link_text"`
	LinkUrl     string         `json:"link_url"`
	Weight      int16          `json:"weight"`
	GroupName   sql.NullString `json:"group_name"`
	ButtonClass string         `json:"button_class"`
	NewWindow   bool           `json:"new_window"`
	OwnerID     uuid.NullUUID  `json:"owner_id"`
}

// CustomLink
// desc: Create a new custom link
func (q *Queries) CreateCustomLink(ctx context.Context, arg CreateCustomLinkParams) error {
	_, err := q.db.ExecContext(ctx, createCustomLink,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.LinkText,
		arg.LinkUrl,
		arg.Weight,
		arg.GroupName,
		arg.ButtonClass,
		arg.NewWindow,
		arg.OwnerID,
	)
	return err
}

const createCustomLinkObjectType = `-- name: CreateCustomLinkObjectType :exec
INSERT INTO extras_customlink_object_types (custom_link_id, content_type) VALUES ($1, $2)
`

type CreateCustomLinkObjectTypeParams struct {
	CustomLinkID types.ID `json:"custom_link_id"`
	ContentType  string   `json:"content_type"`
}

// desc: Associate an object type with a custom link
func (q *Queries) CreateCustomLinkObjectType(ctx context.Context, arg CreateCustomLinkObjectTypeParams) error {
	_, err := q.db.ExecContext(ctx, createCustomLinkObjectType, arg.CustomLinkID, arg.ContentType)
	return err
}

const createEventRule = `-- name: CreateEventRule :exec
INSERT INTO extras_eventrule (id, name, description, event_types, enabled, conditions, action_type, action_object_type, action_object_id, action_data, comments, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateEventRuleParams struct {
	ID               types.ID              `json:"id"`
	Name             string                `json:"name"`
	Description      sql.NullString        `json:"description"`
	EventTypes       []string              `json:"event_types"`
	Enabled          bool                  `json:"enabled"`
	Conditions       pqtype.NullRawMessage `json:"conditions"`
	ActionType       string                `json:"action_type"`
	ActionObjectType string                `json:"action_object_type"`
	ActionObjectID   sql.NullInt64         `json:"action_object_id"`
	ActionData       pqtype.NullRawMessage `json:"action_data"`
	Comments         sql.NullString        `json:"comments"`
	OwnerID          uuid.NullUUID         `json:"owner_id"`
}

// EventRule
// desc: Create a new event rule
func (q *Queries) CreateEventRule(ctx context.Context, arg CreateEventRuleParams) error {
	_, err := q.db.ExecContext(ctx, createEventRule,
		arg.ID,
		arg.Name,
		arg.Description,
		pq.Array(arg.EventTypes),
		arg.Enabled,
		arg.Conditions,
		arg.ActionType,
		arg.ActionObjectType,
		arg.ActionObjectID,
		arg.ActionData,
		arg.Comments,
		arg.OwnerID,
	)
	return err
}

const createEventRuleObjectType = `-- name: CreateEventRuleObjectType :exec
INSERT INTO extras_eventrule_object_types (event_rule_id, content_type) VALUES ($1, $2)
`

type CreateEventRuleObjectTypeParams struct {
	EventRuleID types.ID `json:"event_rule_id"`
	ContentType string   `json:"content_type"`
}

// desc: Associate an object type with an event rule
func (q *Queries) CreateEventRuleObjectType(ctx context.Context, arg CreateEventRuleObjectTypeParams) error {
	_, err := q.db.ExecContext(ctx, createEventRuleObjectType, arg.EventRuleID, arg.ContentType)
	return err
}

const createExportTemplate = `-- name: CreateExportTemplate :exec
INSERT INTO extras_exporttemplate (id, name, description, template_code, mime_type, file_name, file_extension, as_attachment, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateExportTemplateParams struct {
	ID            types.ID       `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	TemplateCode  string         `json:"template_code"`
	MimeType      string         `json:"mime_type"`
	FileName      string         `json:"file_name"`
	FileExtension string         `json:"file_extension"`
	AsAttachment  bool           `json:"as_attachment"`
	OwnerID       uuid.NullUUID  `json:"owner_id"`
}

// ExportTemplate
// desc: Create a new export template
func (q *Queries) CreateExportTemplate(ctx context.Context, arg CreateExportTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createExportTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TemplateCode,
		arg.MimeType,
		arg.FileName,
		arg.FileExtension,
		arg.AsAttachment,
		arg.OwnerID,
	)
	return err
}

const createExportTemplateObjectType = `-- name: CreateExportTemplateObjectType :exec
INSERT INTO extras_exporttemplate_object_types (export_template_id, content_type) VALUES ($1, $2)
`

type CreateExportTemplateObjectTypeParams struct {
	ExportTemplateID types.ID `json:"export_template_id"`
	ContentType      string   `json:"content_type"`
}

// desc: Associate an object type with an export template
func (q *Queries) CreateExportTemplateObjectType(ctx context.Context, arg CreateExportTemplateObjectTypeParams) error {
	_, err := q.db.ExecContext(ctx, createExportTemplateObjectType, arg.ExportTemplateID, arg.ContentType)
	return err
}

const createImageAttachment = `-- name: CreateImageAttachment :exec
INSERT INTO extras_imageattachment (id, object_type, object_id, image, image_height, image_width, name, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateImageAttachmentParams struct {
	ID          types.ID       `json:"id"`
	ObjectType  string         `json:"object_type"`
	ObjectID    int64          `json:"object_id"`
	Image       string         `json:"image"`
	ImageHeight int16          `json:"image_height"`
	ImageWidth  int16          `json:"image_width"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

// ImageAttachment
// desc: Create a new image attachment
func (q *Queries) CreateImageAttachment(ctx context.Context, arg CreateImageAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createImageAttachment,
		arg.ID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Image,
		arg.ImageHeight,
		arg.ImageWidth,
		arg.Name,
		arg.Description,
	)
	return err
}

const createJournalEntry = `-- name: CreateJournalEntry :exec
INSERT INTO extras_journalentry (id, assigned_object_type, assigned_object_id, created_by, kind, comments)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateJournalEntryParams struct {
	ID                 types.ID      `json:"id"`
	AssignedObjectType string        `json:"assigned_object_type"`
	AssignedObjectID   int64         `json:"assigned_object_id"`
	CreatedBy          uuid.NullUUID `json:"created_by"`
	Kind               string        `json:"kind"`
	Comments           string        `json:"comments"`
}

// JournalEntry
// desc: Create a new journal entry
func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) error {
	_, err := q.db.ExecContext(ctx, createJournalEntry,
		arg.ID,
		arg.AssignedObjectType,
		arg.AssignedObjectID,
		arg.CreatedBy,
		arg.Kind,
		arg.Comments,
	)
	return err
}

const createSavedFilter = `-- name: CreateSavedFilter :exec
INSERT INTO extras_savedfilter (id, name, slug, description, user_id, weight, enabled, shared, parameters, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateSavedFilterParams struct {
	ID          types.ID        `json:"id"`
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Description sql.NullString  `json:"description"`
	UserID      uuid.NullUUID   `json:"user_id"`
	Weight      int16           `json:"weight"`
	Enabled     bool            `json:"enabled"`
	Shared      bool            `json:"shared"`
	Parameters  json.RawMessage `json:"parameters"`
	OwnerID     uuid.NullUUID   `json:"owner_id"`
}

// SavedFilter
// desc: Create a new saved filter
func (q *Queries) CreateSavedFilter(ctx context.Context, arg CreateSavedFilterParams) error {
	_, err := q.db.ExecContext(ctx, createSavedFilter,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.UserID,
		arg.Weight,
		arg.Enabled,
		arg.Shared,
		arg.Parameters,
		arg.OwnerID,
	)
	return err
}

const createSavedFilterObjectType = `-- name: CreateSavedFilterObjectType :exec
INSERT INTO extras_savedfilter_object_types (saved_filter_id, content_type) VALUES ($1, $2)
`

type CreateSavedFilterObjectTypeParams struct {
	SavedFilterID types.ID `json:"saved_filter_id"`
	ContentType   string   `json:"content_type"`
}

// desc: Associate an object type with a saved filter
func (q *Queries) CreateSavedFilterObjectType(ctx context.Context, arg CreateSavedFilterObjectTypeParams) error {
	_, err := q.db.ExecContext(ctx, createSavedFilterObjectType, arg.SavedFilterID, arg.ContentType)
	return err
}

const createTableConfig = `-- name: CreateTableConfig :exec
INSERT INTO extras_tableconfig (id, object_type, "table", name, description, user_id, weight, enabled, shared, columns, ordering)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateTableConfigParams struct {
	ID          types.ID       `json:"id"`
	ObjectType  string         `json:"object_type"`
	Table       string         `json:"table"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      uuid.NullUUID  `json:"user_id"`
	Weight      int16          `json:"weight"`
	Enabled     bool           `json:"enabled"`
	Shared      bool           `json:"shared"`
	Columns     []string       `json:"columns"`
	Ordering    []string       `json:"ordering"`
}

// TableConfig
// desc: Create a new table config
func (q *Queries) CreateTableConfig(ctx context.Context, arg CreateTableConfigParams) error {
	_, err := q.db.ExecContext(ctx, createTableConfig,
		arg.ID,
		arg.ObjectType,
		arg.Table,
		arg.Name,
		arg.Description,
		arg.UserID,
		arg.Weight,
		arg.Enabled,
		arg.Shared,
		pq.Array(arg.Columns),
		pq.Array(arg.Ordering),
	)
	return err
}

const createWebhook = `-- name: CreateWebhook :exec
INSERT INTO extras_webhook (id, name, description, payload_url, http_method, http_content_type, additional_headers, body_template, secret, ssl_verification, ca_file_path, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateWebhookParams struct {
	ID                types.ID       `json:"id"`
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	PayloadUrl        string         `json:"payload_url"`
	HttpMethod        string         `json:"http_method"`
	HttpContentType   string         `json:"http_content_type"`
	AdditionalHeaders sql.NullString `json:"additional_headers"`
	BodyTemplate      sql.NullString `json:"body_template"`
	Secret            sql.NullString `json:"secret"`
	SslVerification   bool           `json:"ssl_verification"`
	CaFilePath        sql.NullString `json:"ca_file_path"`
	OwnerID           uuid.NullUUID  `json:"owner_id"`
}

// Webhook
// desc: Create a new webhook
func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) error {
	_, err := q.db.ExecContext(ctx, createWebhook,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PayloadUrl,
		arg.HttpMethod,
		arg.HttpContentType,
		arg.AdditionalHeaders,
		arg.BodyTemplate,
		arg.Secret,
		arg.SslVerification,
		arg.CaFilePath,
		arg.OwnerID,
	)
	return err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM extras_bookmark WHERE id = $1
`

// desc: Delete a bookmark
func (q *Queries) DeleteBookmark(ctx context.Context, id types.ID) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, id)
	return err
}

const deleteCustomLink = `-- name: DeleteCustomLink :exec
DELETE FROM extras_customlink WHERE id = $1
`

// desc: Delete a custom link
func (q *Queries) DeleteCustomLink(ctx context.Context, id types.ID) error {
	_, err := q.db.ExecContext(ctx, deleteCustomLink, id)
	return err
}

const deleteEventRule = `-- name: DeleteEventRule :exec
DELETE FROM extras_eventrule WHERE id = $1
`

// desc: Delete an event rule
func (q *Queries) DeleteEventRule(ctx context.Context, id types.ID) error {
	_, err := q.db.ExecContext(ctx, deleteEventRule, id)
	return err
}

const deleteExportTemplate = `-- name: DeleteExportTemplate :exec
DELETE FROM extras_exporttemplate WHERE id = $1
`

// desc: Delete an export template
func (q *Queries) DeleteExportTemplate(ctx context.Context, id types.ID) error {
	_, err := q.db.ExecContext(ctx, deleteExportTemplate, id)
	return err
}

const deleteImageAttachment = `-- name: DeleteImageAttachment :exec
DELETE FROM extras_imageattachment WHERE id = $1
`

// desc: Delete an image attachment
func (q *Queries) DeleteImageAttachment(ctx context.Context, id types.ID) error {
	_, err := q.db.ExecContext(ctx, deleteImageAttachment, id)
	return err
}

const deleteSavedFilter = `-- name: DeleteSavedFilter :exec
DELETE FROM extras_savedfilter WHERE id = $1
`

// desc: Delete a saved filter
func (q *Queries) DeleteSavedFilter(ctx context.Context, id types.ID) error {
	_, err := q.db.ExecContext(ctx, deleteSavedFilter, id)
	return err
}

const deleteTableConfig = `-- name: DeleteTableConfig :exec
DELETE FROM extras_tableconfig WHERE id = $1
`

// desc: Delete a table config
func (q *Queries) DeleteTableConfig(ctx context.Context, id types.ID) error {
	_, err := q.db.ExecContext(ctx, deleteTableConfig, id)
	return err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM extras_webhook WHERE id = $1
`

// desc: Delete a webhook
func (q *Queries) DeleteWebhook(ctx context.Context, id types.ID) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, id)
	return err
}

const getCustomLink = `-- name: GetCustomLink :one
SELECT id, name, enabled, link_text, link_url, weight, group_name, button_class, new_window, owner_id, created_at, updated_at FROM extras_customlink WHERE id = $1
`

// desc: Get a custom link by ID
func (q *Queries) GetCustomLink(ctx context.Context, id types.ID) (ExtrasCustomlink, error) {
	row := q.db.QueryRowContext(ctx, getCustomLink, id)
	var i ExtrasCustomlink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.LinkText,
		&i.LinkUrl,
		&i.Weight,
		&i.GroupName,
		&i.ButtonClass,
		&i.NewWindow,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventRule = `-- name: GetEventRule :one
SELECT id, name, description, event_types, enabled, conditions, action_type, action_object_type, action_object_id, action_data, comments, owner_id, created_at, updated_at FROM extras_eventrule WHERE id = $1
`

// desc: Get an event rule by ID
func (q *Queries) GetEventRule(ctx context.Context, id types.ID) (ExtrasEventrule, error) {
	row := q.db.QueryRowContext(ctx, getEventRule, id)
	var i ExtrasEventrule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		pq.Array(&i.EventTypes),
		&i.Enabled,
		&i.Conditions,
		&i.ActionType,
		&i.ActionObjectType,
		&i.ActionObjectID,
		&i.ActionData,
		&i.Comments,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExportTemplate = `-- name: GetExportTemplate :one
SELECT id, name, description, template_code, mime_type, file_name, file_extension, as_attachment, owner_id, created_at, updated_at FROM extras_exporttemplate WHERE id = $1
`

// desc: Get an export template by ID
func (q *Queries) GetExportTemplate(ctx context.Context, id types.ID) (ExtrasExporttemplate, error) {
	row := q.db.QueryRowContext(ctx, getExportTemplate, id)
	var i ExtrasExporttemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TemplateCode,
		&i.MimeType,
		&i.FileName,
		&i.FileExtension,
		&i.AsAttachment,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageAttachment = `-- name: GetImageAttachment :one
SELECT id, object_type, object_id, image, image_height, image_width, name, description, created_at, updated_at FROM extras_imageattachment WHERE id = $1
`

// desc: Get an image attachment by ID
func (q *Queries) GetImageAttachment(ctx context.Context, id types.ID) (ExtrasImageattachment, error) {
	row := q.db.QueryRowContext(ctx, getImageAttachment, id)
	var i ExtrasImageattachment
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.ObjectID,
		&i.Image,
		&i.ImageHeight,
		&i.ImageWidth,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, assigned_object_type, assigned_object_id, created_by, kind, comments, created_at, updated_at FROM extras_journalentry WHERE id = $1
`

// desc: Get a journal entry by ID
func (q *Queries) GetJournalEntry(ctx context.Context, id types.ID) (ExtrasJournalentry, error) {
	row := q.db.QueryRowContext(ctx, getJournalEntry, id)
	var i ExtrasJournalentry
	err := row.Scan(
		&i.ID,
		&i.AssignedObjectType,
		&i.AssignedObjectID,
		&i.CreatedBy,
		&i.Kind,
		&i.Comments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSavedFilter = `-- name: GetSavedFilter :one
SELECT id, name, slug, description, user_id, weight, enabled, shared, parameters, owner_id, created_at, updated_at FROM extras_savedfilter WHERE id = $1
`

// desc: Get a saved filter by ID
func (q *Queries) GetSavedFilter(ctx context.Context, id types.ID) (ExtrasSavedfilter, error) {
	row := q.db.QueryRowContext(ctx, getSavedFilter, id)
	var i ExtrasSavedfilter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.UserID,
		&i.Weight,
		&i.Enabled,
		&i.Shared,
		&i.Parameters,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTableConfig = `-- name: GetTableConfig :one
SELECT id, object_type, "table", name, description, user_id, weight, enabled, shared, columns, ordering, created_at, updated_at FROM extras_tableconfig WHERE id = $1
`

// desc: Get a table config by ID
func (q *Queries) GetTableConfig(ctx context.Context, id types.ID) (ExtrasTableconfig, error) {
	row := q.db.QueryRowContext(ctx, getTableConfig, id)
	var i ExtrasTableconfig
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.Table,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Weight,
		&i.Enabled,
		&i.Shared,
		pq.Array(&i.Columns),
		pq.Array(&i.Ordering),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, name, description, payload_url, http_method, http_content_type, additional_headers, body_template, secret, ssl_verification, ca_file_path, owner_id, created_at, updated_at FROM extras_webhook WHERE id = $1
`

// desc: Get a webhook by ID
func (q *Queries) GetWebhook(ctx context.Context, id types.ID) (ExtrasWebhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, id)
	var i ExtrasWebhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PayloadUrl,
		&i.HttpMethod,
		&i.HttpContentType,
		&i.AdditionalHeaders,
		&i.BodyTemplate,
		&i.Secret,
		&i.SslVerification,
		&i.CaFilePath,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT id, object_type, object_id, user_id, created_at FROM extras_bookmark WHERE user_id = $1 ORDER BY created_at
`

// desc: List bookmarks for a user
func (q *Queries) ListBookmarks(ctx context.Context, userID types.ID) ([]ExtrasBookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtrasBookmark{}
	for rows.Next() {
		var i ExtrasBookmark
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomLinkObjectTypes = `-- name: ListCustomLinkObjectTypes :many
SELECT content_type FROM extras_customlink_object_types WHERE custom_link_id = $1
`

// desc: List object types for a custom link
func (q *Queries) ListCustomLinkObjectTypes(ctx context.Context, customLinkID types.ID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCustomLinkObjectTypes, customLinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var content_type string
		if err := rows.Scan(&content_type); err != nil {
			return nil, err
		}
		items = append(items, content_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomLinks = `-- name: ListCustomLinks :many
SELECT id, name, enabled, link_text, link_url, weight, group_name, button_class, new_window, owner_id, created_at, updated_at FROM extras_customlink ORDER BY group_name, weight, name LIMIT $1 OFFSET $2
`

type ListCustomLinksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// desc: List custom links with pagination
func (q *Queries) ListCustomLinks(ctx context.Context, arg ListCustomLinksParams) ([]ExtrasCustomlink, error) {
	rows, err := q.db.QueryContext(ctx, listCustomLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtrasCustomlink{}
	for rows.Next() {
		var i ExtrasCustomlink
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.LinkText,
			&i.LinkUrl,
			&i.Weight,
			&i.GroupName,
			&i.ButtonClass,
			&i.NewWindow,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventRuleObjectTypes = `-- name: ListEventRuleObjectTypes :many
SELECT content_type FROM extras_eventrule_object_types WHERE event_rule_id = $1
`

// desc: List object types for an event rule
func (q *Queries) ListEventRuleObjectTypes(ctx context.Context, eventRuleID types.ID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEventRuleObjectTypes, eventRuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var content_type string
		if err := rows.Scan(&content_type); err != nil {
			return nil, err
		}
		items = append(items, content_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventRules = `-- name: ListEventRules :many
SELECT id, name, description, event_types, enabled, conditions, action_type, action_object_type, action_object_id, action_data, comments, owner_id, created_at, updated_at FROM extras_eventrule ORDER BY name LIMIT $1 OFFSET $2
`

type ListEventRulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// desc: List event rules with pagination
func (q *Queries) ListEventRules(ctx context.Context, arg ListEventRulesParams) ([]ExtrasEventrule, error) {
	rows, err := q.db.QueryContext(ctx, listEventRules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtrasEventrule{}
	for rows.Next() {
		var i ExtrasEventrule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			pq.Array(&i.EventTypes),
			&i.Enabled,
			&i.Conditions,
			&i.ActionType,
			&i.ActionObjectType,
			&i.ActionObjectID,
			&i.ActionData,
			&i.Comments,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportTemplateObjectTypes = `-- name: ListExportTemplateObjectTypes :many
SELECT content_type FROM extras_exporttemplate_object_types WHERE export_template_id = $1
`

// desc: List object types for an export template
func (q *Queries) ListExportTemplateObjectTypes(ctx context.Context, exportTemplateID types.ID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExportTemplateObjectTypes, exportTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var content_type string
		if err := rows.Scan(&content_type); err != nil {
			return nil, err
		}
		items = append(items, content_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportTemplates = `-- name: ListExportTemplates :many
SELECT id, name, description, template_code, mime_type, file_name, file_extension, as_attachment, owner_id, created_at, updated_at FROM extras_exporttemplate ORDER BY name LIMIT $1 OFFSET $2
`

type ListExportTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// desc: List export templates with pagination
func (q *Queries) ListExportTemplates(ctx context.Context, arg ListExportTemplatesParams) ([]ExtrasExporttemplate, error) {
	rows, err := q.db.QueryContext(ctx, listExportTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtrasExporttemplate{}
	for rows.Next() {
		var i ExtrasExporttemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TemplateCode,
			&i.MimeType,
			&i.FileName,
			&i.FileExtension,
			&i.AsAttachment,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImageAttachments = `-- name: ListImageAttachments :many
SELECT id, object_type, object_id, image, image_height, image_width, name, description, created_at, updated_at FROM extras_imageattachment WHERE object_type = $1 AND object_id = $2 ORDER BY name, id
`

type ListImageAttachmentsParams struct {
	ObjectType string `json:"object_type"`
	ObjectID   int64  `json:"object_id"`
}

// desc: List image attachments for a specific object
func (q *Queries) ListImageAttachments(ctx context.Context, arg ListImageAttachmentsParams) ([]ExtrasImageattachment, error) {
	rows, err := q.db.QueryContext(ctx, listImageAttachments, arg.ObjectType, arg.ObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtrasImageattachment{}
	for rows.Next() {
		var i ExtrasImageattachment
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Image,
			&i.ImageHeight,
			&i.ImageWidth,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, assigned_object_type, assigned_object_id, created_by, kind, comments, created_at, updated_at FROM extras_journalentry WHERE assigned_object_type = $1 AND assigned_object_id = $2 ORDER BY created_at DESC
`

type ListJournalEntriesParams struct {
	AssignedObjectType string `json:"assigned_object_type"`
	AssignedObjectID   int64  `json:"assigned_object_id"`
}

// desc: List journal entries for a specific object
func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]ExtrasJournalentry, error) {
	rows, err := q.db.QueryContext(ctx, listJournalEntries, arg.AssignedObjectType, arg.AssignedObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtrasJournalentry{}
	for rows.Next() {
		var i ExtrasJournalentry
		if err := rows.Scan(
			&i.ID,
			&i.AssignedObjectType,
			&i.AssignedObjectID,
			&i.CreatedBy,
			&i.Kind,
			&i.Comments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFilterObjectTypes = `-- name: ListSavedFilterObjectTypes :many
SELECT content_type FROM extras_savedfilter_object_types WHERE saved_filter_id = $1
`

// desc: List object types for a saved filter
func (q *Queries) ListSavedFilterObjectTypes(ctx context.Context, savedFilterID types.ID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSavedFilterObjectTypes, savedFilterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var content_type string
		if err := rows.Scan(&content_type); err != nil {
			return nil, err
		}
		items = append(items, content_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFilters = `-- name: ListSavedFilters :many
SELECT id, name, slug, description, user_id, weight, enabled, shared, parameters, owner_id, created_at, updated_at FROM extras_savedfilter ORDER BY weight, name LIMIT $1 OFFSET $2
`

type ListSavedFiltersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// desc: List saved filters with pagination
func (q *Queries) ListSavedFilters(ctx context.Context, arg ListSavedFiltersParams) ([]ExtrasSavedfilter, error) {
	rows, err := q.db.QueryContext(ctx, listSavedFilters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtrasSavedfilter{}
	for rows.Next() {
		var i ExtrasSavedfilter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.UserID,
			&i.Weight,
			&i.Enabled,
			&i.Shared,
			&i.Parameters,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableConfigs = `-- name: ListTableConfigs :many
SELECT id, object_type, "table", name, description, user_id, weight, enabled, shared, columns, ordering, created_at, updated_at FROM extras_tableconfig ORDER BY weight, name LIMIT $1 OFFSET $2
`

type ListTableConfigsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// desc: List table configs with pagination
func (q *Queries) ListTableConfigs(ctx context.Context, arg ListTableConfigsParams) ([]ExtrasTableconfig, error) {
	rows, err := q.db.QueryContext(ctx, listTableConfigs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtrasTableconfig{}
	for rows.Next() {
		var i ExtrasTableconfig
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.Table,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.Weight,
			&i.Enabled,
			&i.Shared,
			pq.Array(&i.Columns),
			pq.Array(&i.Ordering),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, name, description, payload_url, http_method, http_content_type, additional_headers, body_template, secret, ssl_verification, ca_file_path, owner_id, created_at, updated_at FROM extras_webhook ORDER BY name LIMIT $1 OFFSET $2
`

type ListWebhooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// desc: List webhooks with pagination
func (q *Queries) ListWebhooks(ctx context.Context, arg ListWebhooksParams) ([]ExtrasWebhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtrasWebhook{}
	for rows.Next() {
		var i ExtrasWebhook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PayloadUrl,
			&i.HttpMethod,
			&i.HttpContentType,
			&i.AdditionalHeaders,
			&i.BodyTemplate,
			&i.Secret,
			&i.SslVerification,
			&i.CaFilePath,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomLink = `-- name: UpdateCustomLink :exec
UPDATE extras_customlink 
SET name = $2, enabled = $3, link_text = $4, link_url = $5, weight = $6, group_name = $7, button_class = $8, new_window = $9, owner_id = $10, updated_at = NOW()
WHERE id = $1
`

type UpdateCustomLinkParams struct {
	ID          types.ID       `json:"id"`
	Name        string         `json:"name"`
	Enabled     bool           `json:"enabled"`
	LinkText    string         `json:"link_text"`
	LinkUrl     string         `json:"link_url"`
	Weight      int16          `json:"weight"`
	GroupName   sql.NullString `json:"group_name"`
	ButtonClass string         `json:"button_class"`
	NewWindow   bool           `json:"new_window"`
	OwnerID     uuid.NullUUID  `json:"owner_id"`
}

// desc: Update a custom link
func (q *Queries) UpdateCustomLink(ctx context.Context, arg UpdateCustomLinkParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomLink,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.LinkText,
		arg.LinkUrl,
		arg.Weight,
		arg.GroupName,
		arg.ButtonClass,
		arg.NewWindow,
		arg.OwnerID,
	)
	return err
}

const updateEventRule = `-- name: UpdateEventRule :exec
UPDATE extras_eventrule 
SET name = $2, description = $3, event_types = $4, enabled = $5, conditions = $6, action_type = $7, action_object_type = $8, action_object_id = $9, action_data = $10, comments = $11, owner_id = $12, updated_at = NOW()
WHERE id = $1
`

type UpdateEventRuleParams struct {
	ID               types.ID              `json:"id"`
	Name             string                `json:"name"`
	Description      sql.NullString        `json:"description"`
	EventTypes       []string              `json:"event_types"`
	Enabled          bool                  `json:"enabled"`
	Conditions       pqtype.NullRawMessage `json:"conditions"`
	ActionType       string                `json:"action_type"`
	ActionObjectType string                `json:"action_object_type"`
	ActionObjectID   sql.NullInt64         `json:"action_object_id"`
	ActionData       pqtype.NullRawMessage `json:"action_data"`
	Comments         sql.NullString        `json:"comments"`
	OwnerID          uuid.NullUUID         `json:"owner_id"`
}

// desc: Update an existing event rule
func (q *Queries) UpdateEventRule(ctx context.Context, arg UpdateEventRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateEventRule,
		arg.ID,
		arg.Name,
		arg.Description,
		pq.Array(arg.EventTypes),
		arg.Enabled,
		arg.Conditions,
		arg.ActionType,
		arg.ActionObjectType,
		arg.ActionObjectID,
		arg.ActionData,
		arg.Comments,
		arg.OwnerID,
	)
	return err
}

const updateExportTemplate = `-- name: UpdateExportTemplate :exec
UPDATE extras_exporttemplate 
SET name = $2, description = $3, template_code = $4, mime_type = $5, file_name = $6, file_extension = $7, as_attachment = $8, owner_id = $9, updated_at = NOW()
WHERE id = $1
`

type UpdateExportTemplateParams struct {
	ID            types.ID       `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	TemplateCode  string         `json:"template_code"`
	MimeType      string         `json:"mime_type"`
	FileName      string         `json:"file_name"`
	FileExtension string         `json:"file_extension"`
	AsAttachment  bool           `json:"as_attachment"`
	OwnerID       uuid.NullUUID  `json:"owner_id"`
}

// desc: Update an export template
func (q *Queries) UpdateExportTemplate(ctx context.Context, arg UpdateExportTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateExportTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TemplateCode,
		arg.MimeType,
		arg.FileName,
		arg.FileExtension,
		arg.AsAttachment,
		arg.OwnerID,
	)
	return err
}

const updateImageAttachment = `-- name: UpdateImageAttachment :exec
UPDATE extras_imageattachment 
SET object_type = $2, object_id = $3, image = $4, image_height = $5, image_width = $6, name = $7, description = $8, updated_at = NOW()
WHERE id = $1
`

type UpdateImageAttachmentParams struct {
	ID          types.ID       `json:"id"`
	ObjectType  string         `json:"object_type"`
	ObjectID    int64          `json:"object_id"`
	Image       string         `json:"image"`
	ImageHeight int16          `json:"image_height"`
	ImageWidth  int16          `json:"image_width"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

// desc: Update an image attachment
func (q *Queries) UpdateImageAttachment(ctx context.Context, arg UpdateImageAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, updateImageAttachment,
		arg.ID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Image,
		arg.ImageHeight,
		arg.ImageWidth,
		arg.Name,
		arg.Description,
	)
	return err
}

const updateSavedFilter = `-- name: UpdateSavedFilter :exec
UPDATE extras_savedfilter 
SET name = $2, slug = $3, description = $4, user_id = $5, weight = $6, enabled = $7, shared = $8, parameters = $9, owner_id = $10, updated_at = NOW()
WHERE id = $1
`

type UpdateSavedFilterParams struct {
	ID          types.ID        `json:"id"`
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Description sql.NullString  `json:"description"`
	UserID      uuid.NullUUID   `json:"user_id"`
	Weight      int16           `json:"weight"`
	Enabled     bool            `json:"enabled"`
	Shared      bool            `json:"shared"`
	Parameters  json.RawMessage `json:"parameters"`
	OwnerID     uuid.NullUUID   `json:"owner_id"`
}

// desc: Update a saved filter
func (q *Queries) UpdateSavedFilter(ctx context.Context, arg UpdateSavedFilterParams) error {
	_, err := q.db.ExecContext(ctx, updateSavedFilter,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.UserID,
		arg.Weight,
		arg.Enabled,
		arg.Shared,
		arg.Parameters,
		arg.OwnerID,
	)
	return err
}

const updateTableConfig = `-- name: UpdateTableConfig :exec
UPDATE extras_tableconfig 
SET object_type = $2, "table" = $3, name = $4, description = $5, user_id = $6, weight = $7, enabled = $8, shared = $9, columns = $10, ordering = $11, updated_at = NOW()
WHERE id = $1
`

type UpdateTableConfigParams struct {
	ID          types.ID       `json:"id"`
	ObjectType  string         `json:"object_type"`
	Table       string         `json:"table"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      uuid.NullUUID  `json:"user_id"`
	Weight      int16          `json:"weight"`
	Enabled     bool           `json:"enabled"`
	Shared      bool           `json:"shared"`
	Columns     []string       `json:"columns"`
	Ordering    []string       `json:"ordering"`
}

// desc: Update a table config
func (q *Queries) UpdateTableConfig(ctx context.Context, arg UpdateTableConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateTableConfig,
		arg.ID,
		arg.ObjectType,
		arg.Table,
		arg.Name,
		arg.Description,
		arg.UserID,
		arg.Weight,
		arg.Enabled,
		arg.Shared,
		pq.Array(arg.Columns),
		pq.Array(arg.Ordering),
	)
	return err
}

const updateWebhook = `-- name: UpdateWebhook :exec
UPDATE extras_webhook 
SET name = $2, description = $3, payload_url = $4, http_method = $5, http_content_type = $6, additional_headers = $7, body_template = $8, secret = $9, ssl_verification = $10, ca_file_path = $11, owner_id = $12, updated_at = NOW()
WHERE id = $1
`

type UpdateWebhookParams struct {
	ID                types.ID       `json:"id"`
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	PayloadUrl        string         `json:"payload_url"`
	HttpMethod        string         `json:"http_method"`
	HttpContentType   string         `json:"http_content_type"`
	AdditionalHeaders sql.NullString `json:"additional_headers"`
	BodyTemplate      sql.NullString `json:"body_template"`
	Secret            sql.NullString `json:"secret"`
	SslVerification   bool           `json:"ssl_verification"`
	CaFilePath        sql.NullString `json:"ca_file_path"`
	OwnerID           uuid.NullUUID  `json:"owner_id"`
}

// desc: Update a webhook
func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhook,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PayloadUrl,
		arg.HttpMethod,
		arg.HttpContentType,
		arg.AdditionalHeaders,
		arg.BodyTemplate,
		arg.Secret,
		arg.SslVerification,
		arg.CaFilePath,
		arg.OwnerID,
	)
	return err
}
